import { SnakeDanger, SnakeSpecies } from './types';

export const FREEDOMLAND_SNAKES: SnakeSpecies[] = [
  // --- VENOMOUS ---
  {
    id: 'spectacled-cobra',
    name: 'Spectacled Cobra',
    scientificName: 'Naja naja',
    vernacularNames: 'Nag, Nalla Pambu, Gokhura, Naagmuha',
    dangerLevel: SnakeDanger.VENOMOUS,
    description: "The most iconic snake of the region, famous for its majestic hood and spectacle markings. It is a vital protector of crops as it feeds primarily on rodents.",
    keyFeatures: "Large hood with a spectacle-shaped mark on the back; three dark spots on the throat; hood spreads when threatened.",
    averageLength: "1.0 - 1.5 meters",
    maxLength: "2.2 meters",
    diet: 'Rodents, frogs, toads, birds, and other snakes.',
    habitat: 'Open fields, forests, agricultural lands, and near human settlements.',
    distribution: "Widespread throughout Freedomland's plains and low hills.",
    behaviour: "Diurnal and nocturnal; generally shy but will stand its ground, hiss loudly, and spread its hood if cornered.",
    imageUrl: 'https://static.inaturalist.org/photos/368044618/original.jpeg'
  },
  {
    id: 'russells-viper',
    name: "Russell's Viper",
    scientificName: 'Daboia russelii',
    vernacularNames: 'Kander, Kolaku Mandala, Chandraboda, Gunus',
    dangerLevel: SnakeDanger.VENOMOUS,
    description: "A master of camouflage with a powerful build. It is highly valued for controlling rodent populations in farming areas.",
    keyFeatures: "Triangular head; three rows of dark brown, white-edged spots along the body; loud, deep hiss.",
    averageLength: "1.2 meters",
    maxLength: "1.66 meters",
    diet: 'Rodents, small mammals, and occasionally birds.',
    habitat: 'Grassy plains, scrublands, and agricultural fields.',
    distribution: "Common in open country and coastal regions.",
    behaviour: "Sluggish but strikes with incredible speed; produces a sound similar to a pressure cooker when disturbed.",
    imageUrl: 'https://media.istockphoto.com/id/1180781958/photo/macro-photograph-of-the-extremely-venomous-russells-viper.jpg?s=612x612&w=0&k=20&c=Ru2VC3WQkq92Jd8iQ_QyMi8ZSIk1vdpN5KLSWKTAqgg='
  },
  {
    id: 'common-krait',
    name: 'Common Krait',
    scientificName: 'Bungarus caeruleus',
    vernacularNames: 'Kariyat, Kattuviriyan, Manyar, Gunaa',
    dangerLevel: SnakeDanger.VENOMOUS,
    description: "A glossy, nocturnal hunter that helps maintain ecological balance by preying on other snakes and lizards.",
    keyFeatures: "Glossy black or blue-black body with thin white cross-bands (often in pairs); hexagonal scales along the spine.",
    averageLength: "0.9 meters",
    maxLength: "1.75 meters",
    diet: 'Snakes (including other kraits), lizards, and small mammals.',
    habitat: 'Termite mounds, rat holes, crevices, and often found in gardens.',
    distribution: "Found across a wide variety of habitats in Freedomland.",
    behaviour: "Strictly nocturnal; very passive during the day but active and alert at night.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/21247685/large.jpeg'
  },
  {
    id: 'saw-scaled-viper',
    name: 'Saw-scaled Viper',
    scientificName: 'Echis carinatus',
    vernacularNames: 'Phursa, Surattai Pambu, Bandi',
    dangerLevel: SnakeDanger.VENOMOUS,
    description: "A small but distinctive viper known for its unique warning sound created by rubbing its scales together.",
    keyFeatures: "Small size; keeled scales; light 'bird' or 'cross' mark on the head; zigzag pattern on the side.",
    averageLength: "0.3 - 0.5 meters",
    maxLength: "0.8 meters",
    diet: 'Insects, scorpions, lizards, and small frogs.',
    habitat: 'Arid, sandy, or rocky areas; dry scrub forests.',
    distribution: "Drier regions and rocky terrains.",
    behaviour: "Aggressive when threatened; coils into a 'C' shape and rubs scales to produce a sawing sound.",
    imageUrl: 'https://api.indiansnakes.org/u/1686414365666.jpg'
  },
  {
    id: 'slender-coral-snake',
    name: 'Slender Coral Snake',
    scientificName: 'Calliophis melanurus',
    vernacularNames: 'Pavala Pambu, Coral Snake',
    dangerLevel: SnakeDanger.VENOMOUS,
    description: "One of Freedomland's most elusive and beautiful snakes. It is extremely shy and spends most of its life hidden in leaf litter.",
    keyFeatures: "Slender, light brown body; jet-black head and tail with two yellow spots; bright coral-pink belly.",
    averageLength: "0.25 meters",
    maxLength: "0.5 meters",
    diet: 'Worm snakes and small lizards.',
    habitat: 'Leaf litter, loose soil in gardens and deciduous forests.',
    distribution: "Patchy distribution across the central and southern regions.",
    behaviour: "Gentle and non-aggressive; when stressed, it curls its tail to reveal the bright red underside as a warning.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/89559514/medium.jpeg'
  },
  {
    id: 'bamboo-pit-viper',
    name: 'Bamboo Pit Viper',
    scientificName: 'Trimeresurus gramineus',
    vernacularNames: 'Pachai Viriyan, Haseru Mandala, Green Viper',
    dangerLevel: SnakeDanger.VENOMOUS,
    description: "An arboreal specialist that perfectly mimics green foliage. It uses heat-sensing pits to hunt in the dark.",
    keyFeatures: "Bright green body; triangular head; heat-sensing pits between the eye and nostril; yellow or white side-line.",
    averageLength: "0.6 meters",
    maxLength: "0.9 meters",
    diet: 'Frogs, lizards, small birds, and rodents.',
    habitat: 'Bamboo thickets, rainforests, and hilly tea plantations.',
    distribution: "Predominantly in the hill ranges and high-rainfall forests.",
    behaviour: "Slow-moving; ambush predator that remains motionless for hours waiting for prey.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/223720383/medium.jpg'
  },

  // --- HARMLESS ---
  {
    id: 'brahminy-blind-snake',
    name: 'Brahminy Blind Snake',
    scientificName: 'Indotyphlops braminus',
    vernacularNames: 'Worm Snake, Kuruda Pambu, Pot Snake',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "Often mistaken for an earthworm, this tiny snake is a gardener's friend, preying on ant and termite larvae.",
    keyFeatures: "Shiny smooth scales; uniform dark brown/purple color; blunt tail; eyes reduced to tiny black dots.",
    averageLength: "0.12 meters",
    maxLength: "0.18 meters",
    diet: 'Ant and termite eggs, larvae, and pupae.',
    habitat: 'Garden soil, flower pots, leaf litter, and moist earth.',
    distribution: "Found globally due to the international trade of potted plants.",
    behaviour: "Burrowing; entirely subterranean; moves in a vigorous serpentine motion when exposed.",
    imageUrl: 'https://rewildperth.com.au/rwwp/wp-content/uploads/2020/06/Blind-Snake-Barry-Pitman-2-.jpg'
  },
  {
    id: 'beaked-worm-snake',
    name: 'Beaked Worm Snake',
    scientificName: 'Grypotyphlops acutus',
    vernacularNames: 'Large Blind Snake, Hook-nosed Snake',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "The largest species of blind snake in the region, easily identified by its unique beak-like snout used for digging.",
    keyFeatures: "Hooked, beak-like snout; robust body for a blind snake; pale pinkish-brown or greyish color.",
    averageLength: "0.4 meters",
    maxLength: "0.6 meters",
    diet: 'Earthworms, ant and termite larvae.',
    habitat: 'Soft moist soil in forests and agricultural lands.',
    distribution: "Native to central and western hilly regions.",
    behaviour: "Secretive and burrowing; uses its hooked snout to push through compacted soil.",
    imageUrl: 'https://reptile-database.reptarium.cz/content/photo_rd_06/Letheobia-acutus-03000036375_01.jpg'
  },
  {
    id: 'indian-rock-python',
    name: 'Indian Rock Python',
    scientificName: 'Python molurus',
    vernacularNames: 'Ajgar, Periya Pambu, Hebbaavu',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A massive, non-venomous giant that is a symbol of the wild. They are gentle creatures that only strike if severely provoked.",
    keyFeatures: "Large size; dark arrow mark on the head; irregular brown/grey blotches with dark borders.",
    averageLength: "3.0 meters",
    maxLength: "6.0 meters",
    diet: 'Mammals, birds, and large lizards.',
    habitat: 'Marshes, rocky outcrops near water, and dense forests.',
    distribution: "Found throughout the forested regions near water bodies.",
    behaviour: "Sluggish and slow-moving; excellent swimmers; nocturnal hunters that use constriction.",
    imageUrl: 'https://res.cloudinary.com/roundglass/image/upload/f_auto/q_auto/f_auto/c_limit,w_auto:breakpoints_200_2560_100_5:1265/v1626241409/roundglass/indian-rock-python-on-grass-full-body-girish-choure_ktzwpb.jpg'
  },
  {
    id: 'common-sand-boa',
    name: 'Common Sand Boa',
    scientificName: 'Eryx conicus',
    vernacularNames: 'Mannu Pambu, Russell’s Sand Boa, Baamani',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "This snake mimics the appearance of a Russell's Viper to deter predators, but is entirely harmless to humans.",
    keyFeatures: "Extremely rough, keeled scales; short, blunt tail; irregular dark blotches on a brown/grey body.",
    averageLength: "0.5 meters",
    maxLength: "1.0 meter",
    diet: 'Mice, small rats, and lizards.',
    habitat: 'Sandy soil, loose earth, and dry scrub forests.',
    distribution: "Common in plains and semi-arid regions.",
    behaviour: "Sluggish; spends most of its time buried in sand to ambush prey.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/154883190/medium.jpg'
  },
  {
    id: 'red-sand-boa',
    name: 'Red Sand Boa',
    scientificName: 'Eryx johnii',
    vernacularNames: 'Do-muha, Iruthalai Pambu, Two-headed Snake',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "Famous for its tail that resembles a second head, this snake is a key predator of rodents in dry landscapes.",
    keyFeatures: "Thick, sausage-like body; very blunt tail; uniform reddish-brown or sandy color.",
    averageLength: "0.75 meters",
    maxLength: "1.0 meter",
    diet: 'Rodents and small mammals.',
    habitat: 'Sandy plains, agricultural fields, and semi-arid areas.',
    distribution: "Found in the drier regions of northern and western Freedomland.",
    behaviour: "Gentle and burrowing; when threatened, it hides its head and raises its tail to confuse attackers.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/396080939/medium.jpg'
  },
  {
    id: 'common-wolf-snake',
    name: 'Common Wolf Snake',
    scientificName: 'Lycodon aulicus',
    vernacularNames: 'Kawadiya, Vellikol Pambu, Ghod-karayat',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A common house visitor that is harmless but often confused with the Common Krait. It is an excellent climber.",
    keyFeatures: "White or yellow bands that fade toward the tail; flat, duck-bill shaped head; large teeth for gripping skinks.",
    averageLength: "0.4 meters",
    maxLength: "0.8 meters",
    diet: 'Lizards, skinks, and geckos.',
    habitat: 'Gardens, old buildings, forests, and residential areas.',
    distribution: "Widespread and very common in human environments.",
    behaviour: "Nocturnal and nervous; will bite if picked up but has no venom; active climber.",
    imageUrl: 'https://static.inaturalist.org/photos/320615002/medium.jpg'
  },
  {
    id: 'barred-wolf-snake',
    name: 'Barred Wolf Snake',
    scientificName: 'Lycodon striatus',
    vernacularNames: 'Shaw’s Wolf Snake, Varivarayan',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A smaller relative of the common wolf snake, distinguished by its neat, white or yellow bars on a dark background.",
    keyFeatures: "Clear white or yellow bars; black or dark brown body; slender build; smooth scales.",
    averageLength: "0.3 meters",
    maxLength: "0.45 meters",
    diet: 'Small lizards and geckos.',
    habitat: 'Arid areas, scrub forests, and gardens.',
    distribution: "Common in the northern and western plains.",
    behaviour: "Secretive and nocturnal; hides under stones or in leaf litter during the day.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/87070349/medium.jpg'
  },
  {
    id: 'banded-kukri-snake',
    name: 'Banded Kukri Snake',
    scientificName: 'Oligodon arnensis',
    vernacularNames: 'Kukri Pambu, Banded Kukri',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "Named after the 'Kukri' knife due to its curved teeth, which it uses to slice open reptile eggs.",
    keyFeatures: "Distinct 'V' or 'Y' mark on the head; bold black bands on a reddish-brown body; short, stout tail.",
    averageLength: "0.45 meters",
    maxLength: "0.65 meters",
    diet: 'Reptile eggs, small lizards, and insects.',
    habitat: 'Plains, hills, and residential gardens.',
    distribution: "Widespread throughout peninsular regions.",
    behaviour: "Diurnal and nocturnal; will inflate its body and strike if threatened.",
    imageUrl: 'https://api.indiansnakes.org/u/1649565949783.jpg'
  },
  {
    id: 'streaked-kukri-snake',
    name: 'Streaked Kukri Snake',
    scientificName: 'Oligodon taeniolatus',
    vernacularNames: 'Varivarayan Kukri, Streaked Kukri',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A small, slender snake that is often seen in agricultural lands preying on insects.",
    keyFeatures: "Four thin, dark longitudinal stripes; small dark 'V' on the head; slender build.",
    averageLength: "0.35 meters",
    maxLength: "0.6 meters",
    diet: 'Insects, lizard eggs, and small lizards.',
    habitat: 'Rocky plains, agricultural lands, and scrub forests.',
    distribution: "Widespread in peninsular plains.",
    behaviour: "Gentle and non-aggressive; slow-moving and largely secretive.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/106845945/medium.jpeg'
  },
  {
    id: 'dumerils-black-headed-snake',
    name: "Dumeril's Black-Headed Snake",
    scientificName: 'Sibynophis subpunctatus',
    vernacularNames: 'Karu-thalai Pambu, Black-headed Snake',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A beautiful, slender snake with a jet-black head that is a remarkably fast hunter of lizards.",
    keyFeatures: "Distinct black head with a yellow collar; slender greyish-brown body; small black spots on the spine.",
    averageLength: "0.3 meters",
    maxLength: "0.45 meters",
    diet: 'Small lizards and skinks.',
    habitat: 'Forest floors, leaf litter in hilly areas, and gardens.',
    distribution: "Found in central and southern hill ranges.",
    behaviour: "Extremely fast and agile; active during the day; relies on speed to escape.",
    imageUrl: 'https://calphotos.berkeley.edu/imgs/512x768/0000_0000/1113/3239.jpeg'
  },
  {
    id: 'buff-striped-keelback',
    name: 'Buff-Striped Keelback',
    scientificName: 'Amphiesma stolatum',
    vernacularNames: 'Sita-ki-lat, Nirkol Pambu, Naneti',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "Known as one of the most docile snakes in the world, it is often found in wetlands after rain.",
    keyFeatures: "Two yellow longitudinal stripes along the back; keeled scales; black and white spots between the scales.",
    averageLength: "0.4 meters",
    maxLength: "0.8 meters",
    diet: 'Frogs, toads, and small fish.',
    habitat: 'Wetlands, paddy fields, and gardens during the monsoon.',
    distribution: "Ubiquitous in well-watered regions.",
    behaviour: "Strictly diurnal; very gentle; never bites even when handled roughly.",
    imageUrl: 'https://scontent.fblr1-7.fna.fbcdn.net/v/t39.30808-6/504727612_24293192106933076_7222855068008889416_n.jpg?stp=dst-jpg_s640x640_tt6&_nc_cat=107&ccb=1-7&_nc_sid=aa7b47&_nc_ohc=HlxAo8xu6W0Q7kNvwEcsT7n&_nc_oc=AdmDx-L4hpCnQwd2r7MCTjBxKWyzIxa9v06oVrbvCK8tFWuESQU8Xw0ZhNstN5BKT0w&_nc_zt=23&_nc_ht=scontent.fblr1-7.fna&_nc_gid=YyiW1jQasnOG0fdnGGVD4w&oh=00_Afva7UiOSpY0KgVzhlFrhKzVnxm9L51s662mk5z_g9FC9w&oe=69840B18'
  },
  {
    id: 'olive-keelback',
    name: 'Olive Keelback',
    scientificName: 'Atretium schistosum',
    vernacularNames: 'Pacha-nirkol, Water Snake',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "An aquatic specialist frequently seen in ponds, where it plays a key role in controlling fish and frog populations.",
    keyFeatures: "Olive-green or brown body; pinkish or yellowish belly; small head; nostrils set high on the snout.",
    averageLength: "0.6 meters",
    maxLength: "0.85 meters",
    diet: 'Fish and frogs.',
    habitat: 'Ponds, lakes, rivers, and marshes.',
    distribution: "Throughout the southern and central plains near water.",
    behaviour: "Docile and aquatic; spends most of its time in or near the water.",
    imageUrl: 'https://static.inaturalist.org/photos/101306504/medium.jpg'
  },
  {
    id: 'checkered-keelback',
    name: 'Checkered Keelback',
    scientificName: 'Fowlea piscator',
    vernacularNames: 'Dhodia, Thanni Pambu, Neer-haavu',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A highly active and successful water snake found in almost every freshwater body in Freedomland.",
    keyFeatures: "Checkered pattern of black spots; two black streaks behind the eye; keeled scales; eyes set high.",
    averageLength: "0.8 meters",
    maxLength: "1.5 meters",
    diet: 'Fish and frogs.',
    habitat: 'Lakes, rivers, drains, wells, and paddy fields.',
    distribution: "Found everywhere near freshwater.",
    behaviour: "Diurnal and active; can be bold and defensive, flattening its neck and striking if caught.",
    imageUrl: 'https://punezoo.in/wp-content/uploads/2023/06/Checkered-Keelback-Water-snake-1.jpg'
  },
  {
    id: 'green-keelback',
    name: 'Green Keelback',
    scientificName: 'Rhabdophis plumbicolor',
    vernacularNames: 'Gavatya, Pachai Viriyan (Harmless), Green Keelback',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A thick-bodied green snake that is often confused with pit vipers but is non-venomous and feeds on toads.",
    keyFeatures: "Dull green body; large head; juveniles have a bold black 'V' on the neck.",
    averageLength: "0.5 meters",
    maxLength: "0.9 meters",
    diet: 'Toads and frogs.',
    habitat: 'Hills, moist forests, and grasslands.',
    distribution: "Common in the western hills and central plateaus.",
    behaviour: "Slow-moving and gentle; may flatten its neck like a cobra if threatened.",
    imageUrl: 'https://api.indiansnakes.org/u/1658084095342.jpg'
  },
  {
    id: 'trinket-snake',
    name: 'Trinket Snake',
    scientificName: 'Coelognathus helena',
    vernacularNames: 'Kattu-pambu, Trinket, Helena',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "One of the most beautifully patterned snakes in the region, known for its incredible speed and alertness.",
    keyFeatures: "Dark horizontal bands on the forebody; two black stripes on the tail; dark 'spectacle' marks behind the eye.",
    averageLength: "0.7 meters",
    maxLength: "1.5 meters",
    diet: 'Rodents and lizards.',
    habitat: 'Gardens, forests, and rocky terrain.',
    distribution: "Widespread throughout the plains and low hills.",
    behaviour: "Diurnal and active; very fast; will coil and strike rapidly if cornered.",
    imageUrl: 'https://static.inaturalist.org/photos/91817498/large.jpg'
  },
  {
    id: 'rat-snake',
    name: 'Rat Snake',
    scientificName: 'Ptyas mucosa',
    vernacularNames: 'Dhaman, Jerri-pothu, Kere-haavu',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "The fastest snake in the region. It is the farmer's best friend, consuming thousands of rodents throughout its life.",
    keyFeatures: "Large eyes; black lip scales; yellowish-brown or olive-green body; whip-like tail.",
    averageLength: "1.8 meters",
    maxLength: "3.5 meters",
    diet: 'Rodents, frogs, birds, and lizards.',
    habitat: 'Open fields, urban gardens, and agricultural lands.',
    distribution: "Found everywhere in Freedomland.",
    behaviour: "Diurnal and extremely active; flees quickly from humans; may hiss and bite if grabbed.",
    imageUrl: 'https://res.cloudinary.com/roundglass/image/upload/f_auto/q_auto/f_auto/c_limit,w_auto:breakpoints_200_2560_100_5:1265/v1724747049/rg/collective/media/indian-rat-snake-yellow-morph-rajesh-sanap-1724747049231.jpg'
  },
  {
    id: 'banded-racer',
    name: 'Banded Racer',
    scientificName: 'Platyceps plinii',
    vernacularNames: 'Banded Racer, Pliny’s Racer',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A slender, fast-moving hunter found in the rocky scrublands of the central plateau.",
    keyFeatures: "Slender build; greyish-brown body with dark cross-bands; very long tail.",
    averageLength: "0.6 meters",
    maxLength: "1.1 meters",
    diet: 'Lizards and small mammals.',
    habitat: 'Rocky hills, arid scrub forests, and semi-deserts.',
    distribution: "Native to the central and western plateaus.",
    behaviour: "Diurnal; extremely fast; relies on speed and camouflage for survival.",
    imageUrl: 'https://d1hjkbq40fs2x4.cloudfront.net/2021-09-12/files/16313789910.jpeg'
  },
  {
    id: 'bronzeback-tree-snake',
    name: 'Bronzeback Tree Snake',
    scientificName: 'Dendrelaphis tristis',
    vernacularNames: 'Komberi Mookan, Tree Snake',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A graceful tree-dweller that moves like liquid bronze through the canopy.",
    keyFeatures: "Bronze or golden stripe on the back; slender body; large eyes; long pointed snout.",
    averageLength: "1.0 meter",
    maxLength: "1.5 meters",
    diet: 'Frogs, lizards, and small birds.',
    habitat: 'Trees, bushes, and garden hedges.',
    distribution: "Found throughout forests, parks, and wooded gardens.",
    behaviour: "Diurnal; expert climber; capable of jumping between branches.",
    imageUrl: 'https://api.indiansnakes.org/u/1658171207410.jpg'
  },
  {
    id: 'green-vine-snake',
    name: 'Green Vine Snake',
    scientificName: 'Ahaetulla nasuta',
    vernacularNames: 'Kannu-pambu, Hasiru Haavu, Vine Snake',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A master of disguise that looks exactly like a thin vine. It is completely harmless and has a unique pointed snout.",
    keyFeatures: "Leaf-green color; horizontal pupil; very long, pointed snout; slender body.",
    averageLength: "1.0 meter",
    maxLength: "2.0 meters",
    diet: 'Lizards and frogs.',
    habitat: 'Shrubs, low trees, and plantations.',
    distribution: "Common in hill ranges and high-rainfall areas.",
    behaviour: "Diurnal; moves with a swaying motion like a twig in the wind.",
    imageUrl: 'https://live.staticflickr.com/4125/5061234407_6ac8d297e2_b.jpg'
  },
  {
    id: 'common-cat-snake',
    name: 'Common Cat Snake',
    scientificName: 'Boiga trigonata',
    vernacularNames: 'Poonai Pambu, Cat Snake, Gamma',
    dangerLevel: SnakeDanger.HARMLESS,
    description: "A nocturnal climber with large eyes that help it hunt birds and lizards under the stars.",
    keyFeatures: "Large, bulging eyes with vertical pupils; thin neck; greyish body with dark zigzag marks.",
    averageLength: "0.6 meters",
    maxLength: "1.2 meters",
    diet: 'Birds, lizards, and small mammals.',
    habitat: 'Trees, shrubs, and old roofs.',
    distribution: "Widespread across Freedomland.",
    behaviour: "Nocturnal and arboreal; when threatened, it converts into a tight 'S' and strikes, though it is harmless.",
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/320844753/medium.jpeg'
  }
];