import { SnakeDanger, SnakeSpecies } from './types';

export const FREEDOMLAND_SNAKES: SnakeSpecies[] = [
  // HARMLESS SPECIES (20)
  {
    id: 'brahminy-blind-snake',
    name: { en: 'Brahminy Blind Snake', hi: 'अंधा सांप', kn: 'ಹುಳ ಹಾವು', ta: 'சீர் பாம்பு', mr: 'अंधा साप' },
    scientificName: 'Indotyphlops brahminus',
    vernacularNames: { en: 'Flowerpot Snake', hi: 'अंधा सांप', kn: 'ಹುಳ ಹಾವು', ta: 'சீர் பாம்பு', mr: 'अंधा साप' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: {
      en: "The smallest snake in India, often mistaken for an earthworm. They are all female and reproduce as clones of their mother.",
      hi: "भारत का सबसे छोटा सांप, जिसे अक्सर केंचुआ समझ लिया जाता है। ये सभी मादा होती हैं और क्लोन के रूप में प्रजनन करती हैं।",
      kn: "ಭಾರತದ ಅತಿ ಸಣ್ಣ ಹಾವು, ಇದನ್ನು ಎರೆಹುಳು ಎಂದು ತಪ್ಪಾಗಿ ತಿಳಿಯಲಾಗುತ್ತದೆ. ಇವೆಲ್ಲವೂ ಹೆಣ್ಣು ಹಾವುಗಳಾಗಿರುತ್ತವೆ.",
      ta: "இந்தியாவின் மிகச்சிறிய பாம்பு, இது பெரும்பாலும் மண்புழு என்று தவறாகக் கருதப்படுகிறது.",
      mr: "भारतातील सर्वात लहान साप, ज्याला अनेकदा गांडूळ समजले जाते. यात फक्त मादीच असते."
    },
    keyFeatures: { en: "Small, wormlike; smooth, shiny scales; blunt head and tail; no pattern.", hi: "छोटा, केंचुए जैसा; चमकदार शल्क; कुंद सिर और पूंछ।", kn: "ಸಣ್ಣ ಗಾತ್ರ; ನಯವಾದ ಚರ್ಮ; ಮೊಂಡಾದ ತಲೆ ಮತ್ತು ಬಾಲ; ಯಾವುದೇ ಗುರುತುಗಳಿಲ್ಲ.", ta: "சிறியது, மண்புழு போன்றது; மென்மையான செதில்கள்; மழுங்கிய தலை.", mr: "लहान, गांडुळासारखा; चकचकीत खवले; तोंड आणि शेपूट बोथट." },
    averageLength: "12 cm", maxLength: "23 cm",
    diet: { en: 'Tiny worms, ant and termite larvae.', hi: 'छोटे कीड़े, चींटी और दीमक के अंडे।', kn: 'ಚಿಕ್ಕ ಹುಳುಗಳು, ಇರುವೆ ಮತ್ತು ಗೆದ್ದಲುಗಳ ಲಾರ್ವಾ.', ta: 'சிறு புழுக்கள், எறும்பு மற்றும் கரையான் புழுக்கள்.', mr: 'बारीक अळ्या, मुंग्या आणि वाळवीच्या अळ्या.' },
    habitat: { en: 'Underground in ant and termite nests, flowerpots, moist leaves.', hi: 'जमीन के नीचे, दीमक के घोंसले, गमले।', kn: 'ನೆಲದ ಅಡಿ, ಇರುವೆ ಗೂಡುಗಳು, ಹೂವಿನ ಕುಂಡಗಳು.', ta: 'நிலத்தடி, கரையான் புற்றுகள், பூந்தொட்டிகள்.', mr: 'जमिनीत, वारुळे, कुंडीत, ओल्या पानांखाली.' },
    distribution: { en: "Throughout Freedomland.", hi: "पूरे फ्रीडमलैंड में।", kn: "ಎಲ್ಲಾ ಕಡೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "எங்கும் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Nocturnal; hides during day; exudes foul smell and pokes with tail if captured.", hi: "रात्रिचर; दिन में छिपता है; पकड़े जाने पर बदबू छोड़ता है।", kn: "ನಿಶಾಚರಿ; ಹಗಲಿನಲ್ಲಿ ಅಡಗಿರುತ್ತದೆ; ಹಿಡಿದರೆ ಕೆಟ್ಟ ವಾಸನೆ ಸೂಸುತ್ತದೆ.", ta: "இரவு நேரமானது; பிடித்தால் துர்நாற்றம் வீசும்.", mr: "रात्री फिरणारा; दिवसा लपून राहतो; पकडल्यास दुर्गंधी सोडतो." },
    imageUrl: 'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/116/2020/10/IMG_3699-2.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'beaked-worm-snake',
    name: { en: 'Beaked Worm Snake', hi: 'अंधा सांप (चोंच वाला)', kn: 'ಹುಳ ಹಾವು (ಮೂತಿ)', ta: 'சீர் பாம்பு (மூக்கு)', mr: 'अंधा साप (चोचीसारखा)' },
    scientificName: 'Grypotyphlops acutus',
    vernacularNames: { en: 'Beaked Blind Snake', hi: 'अंधा सांप', kn: 'ಹುಳ ಹಾವು', ta: 'சீர் பாம்பு', mr: 'अंधा साप' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: {
      en: "The largest blind snake in India. Its coloration ranges from olive to pink with latticed dots.",
      hi: "भारत का सबसे बड़ा अंधा सांप। इसका रंग जैतूनी से गुलाबी तक हो सकता है।",
      kn: "ಭಾರತದ ಅತಿ ದೊಡ್ಡ ಹುಳ ಹಾವು. ಇದರ ಬಣ್ಣ ಆಲಿವ್‌ನಿಂದ ಗುಲಾಬಿ ಬಣ್ಣದವರೆಗೆ ಇರುತ್ತದೆ.",
      ta: "இந்தியாவின் மிகப்பெரிய சீர் பாம்பு. இது ஆலிவ் முதல் இளஞ்சிவப்பு நிறம் வரை காணப்படும்.",
      mr: "भारतातील सर्वात मोठा अंधा साप. याचा रंग जैतुनी किंवा गुलाबी असतो."
    },
    keyFeatures: { en: "Stout, wormlike; pointed beak-like structure on lip; blunt tail.", hi: "मोटा शरीर; होंठ पर चोंच जैसी संरचना।", kn: "ದಪ್ಪ ದೇಹ; ಮೂತಿಯ ಮೇಲೆ ಚೂಪಾದ ರಚನೆ; ಮೊಂಡಾದ ಬಾಲ.", ta: "தடித்த உடல்; அலகு போன்ற அமைப்பு; மழுங்கிய வால்.", mr: "जाड शरीर; चोचीसारखे नाक; आखूड शेपटी." },
    averageLength: "40 cm", maxLength: "63 cm",
    diet: { en: 'Worms and insects.', hi: 'केंचुए और कीड़े।', kn: 'ಹುಳುಗಳು ಮತ್ತು ಕೀಟಗಳು.', ta: 'புழுக்கள் மற்றும் பூச்சிகள்.', mr: 'किडे आणि अळ्या.' },
    habitat: { en: 'Underground in ant and termite nests, moist leaves.', hi: 'दीमक के टीले, गीली पत्तियां।', kn: 'ಗೆದ್ದಲು ಗೂಡುಗಳು, ಮಣ್ಣಿನ ಅಡಿ.', ta: 'கரையான் புற்றுகள், நிலத்தடி.', mr: 'वारुळे, जमिनीखाली.' },
    distribution: { en: "Central and South Freedomland.", hi: "मध्य और दक्षिण फ्रीडमलैंड।", kn: "ಮಧ್ಯ ಮತ್ತು ದಕ್ಷಿಣ ಭಾಗಗಳಲ್ಲಿ ಕಂಡುಬರುತ್ತದೆ.", ta: "மத்திய மற்றும் தெற்கு ஃப்ரீடம்லேண்ட்.", mr: "मध्य आणि दक्षिण फ्रीडमलँड." },
    behaviour: { en: "Secretive and nocturnal; emerges only after heavy rain. Agile and relies on smell.", hi: "रात्रिचर; भारी बारिश के बाद बाहर निकलता है।", kn: "ನಿಶಾಚರಿ; ಭಾರಿ ಮಳೆಯ ನಂತರ ಮಾತ್ರ ಹೊರಬರುತ್ತದೆ.", ta: "இரவு நேரமானது; கனமழைக்குப் பிறகு வெளியே வரும்.", mr: "रात्री फिरणारा; मुसळधार पावसानंतरच बाहेर पडतो." },
    imageUrl: 'https://reptile-database.reptarium.cz/content/photo_rd_06/Letheobia-acutus-03000036375_01.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'indian-rock-python',
    name: { en: 'Indian Rock Python', hi: 'अजगर', kn: 'ಹೆಬ್ಬಾವು', ta: 'மலைப்பாம்பு', mr: 'अजगर' },
    scientificName: 'Python molurus',
    vernacularNames: { en: 'Ajgar, Periya Pambu', hi: 'अजगर, चित्ती', kn: 'ಹೆಬ್ಬಾವು, ಅಜಗರ', ta: 'மலைப்பாம்பு, பெரிய பாம்பு', mr: 'अजगर' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: {
      en: "A massive giant with heat-sensing pits. Ambush hunters that strangle prey in their powerful coils.",
      hi: "एक विशाल सांप जिसमें गर्मी महसूस करने वाले गड्ढे होते हैं। यह शिकार को दबाकर मारता है।",
      kn: "ಬೃಹತ್ ಗಾತ್ರದ ಹಾವು. ಇದು ಪ್ರಾಣಿಗಳನ್ನು ಸುತ್ತುವರಿಯುವ ಮೂಲಕ ಉಸಿರುಗಟ್ಟಿಸಿ ಕೊಲ್ಲುತ್ತದೆ.",
      ta: "மிகப்பெரிய விஷமற்ற பாம்பு. இது இரையைச் சுருட்டிப் பிடித்துக் கொல்லும்.",
      mr: "एक महाकाय बिनविषारी साप. हा शिकारीला आपल्या विळख्यात पकडून मारतो."
    },
    keyFeatures: { en: "Long, thick; blotched pattern; vertical pupil; big arrow-shaped mark on head.", hi: "लंबा, मोटा; धब्बेदार पैटर्न; सिर पर तीर का निशान।", kn: "ಉದ್ದ ಮತ್ತು ದಪ್ಪ; ದೇಹದ ಮೇಲೆ ಮಚ್ಚೆಗಳು; ತಲೆಯ ಮೇಲೆ ಬಾಣದ ಗುರುತು.", ta: "நீண்ட தடித்த உடல்; உடல் முழுவதும் திட்டுகள்; தலையில் அம்பு அடையாளம்.", mr: "जाड शरीर; अंगावर ठिपके; डोळ्यांची बाहुली उभी; डोक्यावर बाणाची खूण." },
    averageLength: "2-4 m", maxLength: "5.5 m",
    diet: { en: 'Mice, Bandicoots, Birds, Civets, Monitor Lizards, Deer and Wild Boar.', hi: 'चूहे, पक्षी, जंगली बिल्ली, हिरण और जंगली सूअर।', kn: 'ಇಲಿಗಳು, ಪಕ್ಷಿಗಳು, ಸಣ್ಣ ಪ್ರಾಣಿಗಳು, ಜಿಂಕೆ ಮತ್ತು ಕಾಡು ಹಂದಿ.', ta: 'எலிகள், பறவைகள், உடும்புகள், மான் மற்றும் காட்டுப்பன்றி.', mr: 'उंदीर, घूस, पक्षी, भेकर, हरिण आणि रानडुक्कर.' },
    habitat: { en: 'Grasslands, swamps, marshes, woodlands, open forest near water.', hi: 'घास के मैदान, दलदल, जलाशय के पास जंगल।', kn: 'ಹುಲ್ಲುಗಾವಲುಗಳು, ಜೌಗು ಪ್ರದೇಶಗಳು, ನೀರಿನ ಹತ್ತಿರದ ಅರಣ್ಯಗಳು.', ta: 'புல்வெளிகள், சதுப்பு நிலங்கள், நீர்நிலைகளுக்கு அருகிலுள்ள வனப்பகுதிகள்.', mr: 'गवताळ प्रदेश, दलदल, पाण्याजवळील जंगले.' },
    distribution: { en: "Widespread near water bodies.", hi: "जलाशयों के पास।", kn: "ನೀರಿನ ಆಕರಗಳ ಸಮೀಪ ವ್ಯಾಪಕವಾಗಿ ಕಂಡುಬರುತ್ತದೆ.", ta: "நீர்நிலைகளுக்கு அருகில் பரவலாகக் காணப்படுகிறது.", mr: "पाण्याजवळ सर्वत्र आढळतो." },
    behaviour: { en: "Slow moving; excellent swimmers; bask in sun during day; female guards up to 100 eggs.", hi: "सुस्त; बेहतरीन तैराक; मादा 100 अंडों तक की रक्षा करती है।", kn: "ತುಂಬಾ ನಿಧಾನವಾಗಿ ಚಲಿಸುತ್ತದೆ; ಅತ್ಯುತ್ತಮ ಈಜುಗಾರ; ಮರ ಹತ್ತುವುದರಲ್ಲಿ ನಿಪುಣ.", ta: "மெதுவாக நகரக்கூடியது; சிறந்த நீச்சல் வீரர்; 100 முட்டைகள் வரை இடும்.", mr: "संथ हालचाली; उत्कृष्ट पोहणारा; मादी शंभर अंड्यांचे रक्षण करते." },
    imageUrl: 'https://res.cloudinary.com/roundglass/image/upload/f_auto/q_auto/f_auto/c_limit,w_auto:breakpoints_200_2560_100_5:1265/v1626241409/roundglass/indian-rock-python-on-grass-full-body-girish-choure_ktzwpb.jpg',
    iucnStatus: 'Near Threatened'
  },
  {
    id: 'common-sand-boa',
    name: { en: 'Common Sand Boa', hi: 'मिट्टी का सांप', kn: 'ಮರಳು ಹಾವು', ta: 'மண்ணு பாம்பு', mr: 'मांडूळ' },
    scientificName: 'Eryx conicus',
    vernacularNames: { en: 'Russells Sand Boa', hi: 'बामनी', kn: 'ಮರಳು ಹಾವು', ta: 'மண்ணுளி', mr: 'मांडूळ' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Short and thick snake often confused with Russell's Viper. Waits in soil for prey.", hi: "वाइपर जैसा दिखने वाला मोटा सांप। मिट्टी में छिपकर शिकार करता है।", kn: "ಮಂಡಲ ಹಾವಿನಂತೆ ಮಚ್ಚೆಗಳಿರುವ ಗಿಡ್ಡ ಮತ್ತು ದಪ್ಪ ಹಾವು. ಮಣ್ಣಿನಲ್ಲಿ ಅಡಗಿ ಬೇಟೆಯಾಡುತ್ತದೆ.", ta: "கண்ணாடி விரியனைப் போன்ற அமைப்புகளைக் கொண்ட தடித்த பாம்பு. மண்ணில் பதுங்கி வேட்டையாடும்.", mr: "घोणसासारख्या खुणा असलेला जाड साप. जमिनीखाली राहून शिकार करतो." },
    keyFeatures: { en: "Short, thick-bodied; blotched pattern; keeled scales; very rough tail.", hi: "छोटा, मोटा शरीर; खुरदुरे शल्क; बहुत खुरदरी पूंछ।", kn: "ಗಿಡ್ಡ ಮತ್ತು ದಪ್ಪ ಮೈ; ಒರಟಾದ ಚರ್ಮ; ಮೊಂಡಾದ ಬಾಲ.", ta: "குட்டையான தடித்த உடல்; சொரசொரப்பான செதில்கள்; மழுங்கிய வால்.", mr: "आखूड जाड शरीर; खडबडीत खवले; शेपूट खूप खडबडीत." },
    averageLength: "0.5 m", maxLength: "1 m",
    diet: { en: 'Rodents, Lizards, Birds, Frogs and Toads.', hi: 'चूहे, छिपकली, पक्षी और मेंढक।', kn: 'ಇಲಿಗಳು, ಹಲ್ಲಿಗಳು, ಪಕ್ಷಿಗಳು ಮತ್ತು ಕಪ್ಪೆಗಳು.', ta: 'எலிகள், பல்லிகள், பறவைகள் மற்றும் தவளைகள்.', mr: 'उंदीर, सरडे, पक्षी आणि बेडूक.' },
    habitat: { en: 'Sandy areas, rat burrows, underneath rubble and leaf litter.', hi: 'रेतीली मिट्टी, बिल, पत्थरों के नीचे।', kn: 'ಮರಳು ಭೂಮಿ, ಇಲಿ ಬಿಲಗಳು, ಕಲ್ಲುಗಳ ಅಡಿ.', ta: 'மணல் நிலம், எலி வளைகள், பாறை பகுதிகள்.', mr: 'वालुकामय जमीन, उंदराची बिळे, खडकाळ भाग.' },
    distribution: { en: "Widespread in drier areas.", hi: "शुष्क क्षेत्रों में।", kn: "ಒಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ಎಲ್ಲಾ ಕಡೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "வறண்ட பகுதிகளில் பரவலாகக் காணப்படுகிறது.", mr: "कोरड्या प्रदेशात सर्वत्र आढळतो." },
    behaviour: { en: "Ambush hunter; wait in soil with just head out; shy and coils into ball when threatened.", hi: "मिट्टी में सिर निकालकर इंतजार करता है; शर्मीला।", kn: "ಮಣ್ಣಿನಲ್ಲಿ ಅಡಗಿ ಬೇಟೆಯಾಡುತ್ತದೆ; ನಾಚಿಕೆ ಸ್ವಭಾವದ ಹಾವು.", ta: "மண்ணில் பதுங்கி இருந்து வேட்டையாடும்; அமைதியானது.", mr: "जमिनीत डोके काढून दबा धरून बसतो; लाजाळू." },
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/154883190/medium.jpg',
    iucnStatus: 'Near Threatened'
  },
  {
    id: 'red-sand-boa',
    name: { en: 'Red Sand Boa', hi: 'दोमुंहा सांप', kn: 'ಮಣ್ಣು ಮುಕ್ಕ', ta: 'இருதலையன் பாம்பு', mr: 'मांडूळ' },
    scientificName: 'Eryx johnii',
    vernacularNames: { en: 'Johns Sand Boa', hi: 'दोमुंहा', kn: 'ಇರುತಲೆ ಹಾವು', ta: 'மண்ணுளிப் பாம்பு', mr: 'मांडूळ' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "A blunt-tailed boa often wrongly believed to have two heads. A docile nocturnal constrictor.", hi: "आखूड पूंछ वाला सांप जिसे लोग दोमुंहा कहते हैं। शांत स्वभाव का।", kn: "ಮೊಂಡಾದ ಬಾಲವಿರುವುದರಿಂದ ಇದಕ್ಕೆ ಎರಡು ತಲೆಗಳಿವೆ ಎಂಬ ತಪ್ಪು ನಂಬಿಕೆ ಇದೆ.", ta: "மழுங்கிய வால் கொண்ட பாம்பு; இதற்கு இரண்டு தலைகள் இருப்பதாக நம்பப்படுகிறது.", mr: "दोन तोंडे असल्याचा गैरसमज असणारा साप. रात्री वावरतो." },
    keyFeatures: { en: "Blunt tail mimicking head; thick body; protruding snout for digging.", hi: "कुंद पूंछ; उभरी हुई नाक; मोतियों जैसे शल्क।", kn: "ಮೊಂಡಾದ ಬಾಲ; ಚೂಪಾದ ಮೂತಿ; ಮಚ್ಚೆಗಳಿಲ್ಲದ ಮೈ.", ta: "மழுங்கிய வால்; நீட்டிக்கொண்டிருக்கும் மூக்கு; மணிகள் போன்ற செதில்கள்.", mr: "शेपूट तोंडासारखी दिसते; अणकुचीदार नाक; ठिपके नसलेले शरीर." },
    averageLength: "0.75 m", maxLength: "1 m",
    diet: { en: 'Rodents, Lizards, Birds, Frogs and Toads.', hi: 'चूहे, छिपकली और मेंढक।', kn: 'ಇಲಿಗಳು, ಹಲ್ಲಿಗಳು ಮತ್ತು ಕಪ್ಪೆಗಳು.', ta: 'எலிகள், பல்லிகள் மற்றும் தவளைகள்.', mr: 'उंदीर, सरडे आणि बेडूक.' },
    habitat: { en: 'Sandy areas with plenty of burrows and thickets.', hi: 'रेतीली मिट्टी और घनी झाड़ियां।', kn: 'ಮರಳು ಭೂಮಿ ಮತ್ತು ಪೊದೆಗಳು.', ta: 'மணல் நிறைந்த பகுதிகள் மற்றும் புதர்கள்.', mr: 'वालुकामय जमीन आणि झुडपे.' },
    distribution: { en: "Arid regions and loose soil zones.", hi: "शुष्क क्षेत्र।", kn: "ಒಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ಕಂಡುಬರುತ್ತದೆ.", ta: "வறண்ட நிலப்பரப்புகள்.", mr: "कोरडे प्रदेश." },
    behaviour: { en: "Docile; waves blunt tail to distract predators; skilful digger.", hi: "शांत; अपनी पूंछ का उपयोग शिकारी को भ्रमित करने के लिए करता है।", kn: "ಶಾಂತ ಸ್ವಭಾವ; ಬಾಲವನ್ನು ತಲೆಯಂತೆ ಆಡಿಸಿ ಶತ್ರುಗಳನ್ನು ದಾರಿತಪ್ಪಿಸುತ್ತದೆ.", ta: "அமைதியானது; எதிரிகளை ஏமாற்ற வாலைத் தலை போல ஆட்டும்.", mr: "अतिशय शांत; शेपटीने तोंडाची नक्कल करून शत्रूला फसवतो." },
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/396080939/medium.jpg',
    iucnStatus: 'Near Threatened'
  },
  {
    id: 'common-wolf-snake',
    name: { en: 'Common Wolf Snake', hi: 'सांखड़', kn: 'ತೋಳ ಹಾವು', ta: 'வெள்ளிக்கோல் வரையன்', mr: 'कवड्या' },
    scientificName: 'Lycodon aulicus',
    vernacularNames: { en: 'Wolf Snake', hi: 'कौड़िया', kn: 'ಇಲಿ ಹಾವು', ta: 'வெள்ளைக்கட்டு விரியன்', mr: 'कवड्या' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Small, slender nocturnal climber. Often confused with Kraits due to white cross-bands.", hi: "छोटा, रात में सक्रिय और दीवारों पर चढ़ने वाला सांप।", kn: "ರಾತ್ರಿ ವೇಳೆ ಸಂಚರಿಸುವ ಗೋಡೆ ಹತ್ತುವ ಸಣ್ಣ ಹಾವು.", ta: "இரவில் செயல்படும் மெலிந்த பாம்பு. இது கட்டுவிரியன் போலத் தோன்றும்.", mr: "रात्री फिरणारा आणि भिंतीवर चढणारा लहान बिनविषारी साप." },
    keyFeatures: { en: "Slender; white cross bands; protruding black eyes; glossy scales.", hi: "पतला शरीर; सफेद धारियां; उभरी हुई काली आंखें।", kn: "ತೆಳುವಾದ ಮೈ; ಬಿಳಿ ಪಟ್ಟಿಗಳಿರಬಹುದು; ಚೂಪಾದ ಕಣ್ಣುಗಳು.", ta: "மெலிந்த உடல்; வெள்ளை பட்டைகள்; துருத்திய கண்கள்.", mr: "बारीक शरीर; पांढरे पट्टे; डोळे काळे आणि थोडे बाहेर आलेले." },
    averageLength: "30 cm", maxLength: "80 cm",
    diet: { en: 'Skinks, lizards, frogs.', hi: 'छिपकली और मेंढक।', kn: 'ಹಲ್ಲಿಗಳು ಮತ್ತು ಕಪ್ಪೆಗಳು.', ta: 'பல்லிகள் மற்றும் தவளைகள்.', mr: 'पाल, सरडे आणि बेडूक.' },
    habitat: { en: 'Old buildings, gardens, pile of rocks, rat burrows.', hi: 'पुरानी इमारतें, बगीचे।', kn: 'ಹಳೆಯ ಕಟ್ಟಡಗಳು, ತೋಟಗಳು.', ta: 'பழைய கட்டிடங்கள், தோட்டங்கள்.', mr: 'जुनी घरे, बागा.' },
    distribution: { en: "Widespread near human habitations.", hi: "बस्तियों के पास आम।", kn: "ಮನುಷ್ಯರ ವಾಸಸ್ಥಳದ ಹತ್ತಿರ ಸಾಮಾನ್ಯ.", ta: "மனித குடியிருப்புகளுக்கு அருகில் அதிகம்.", mr: "मानवी वस्तीजवळ आढळतो." },
    behaviour: { en: "Nocturnal; excellent climber; becomes snappy if cornered.", hi: "रात्रिचर; दीवारों पर चढ़ने में माहिर।", kn: "ನಿಶಾಚರಿ; ಗೋಡೆ ಹತ್ತುವುದರಲ್ಲಿ ನಿಪುಣ.", ta: "இரவு நேரமானது; சுவர்களில் ஏறும் தன்மையுடையது.", mr: "रात्री शिकारीसाठी फिरतो; भिंतीवर सहज चढतो." },
    imageUrl: 'https://static.inaturalist.org/photos/260682163/medium.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'barred-wolf-snake',
    name: { en: 'Barred Wolf Snake', hi: 'कौड़िया (पट्टेदार)', kn: 'ಪಟ್ಟಿಯ ತೋಳ ಹಾವು', ta: 'வரி வெள்ளைக்கட்டு விரியன்', mr: 'कवड्या (पट्टेरी)' },
    scientificName: 'Lycodon striatus',
    vernacularNames: { en: 'Wolf Snake', hi: 'कौड़िया', kn: 'ಇಲಿ ಹಾವು', ta: 'வெள்ளைக்கட்டு விரியன்', mr: 'कवड्या' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Small, secretive wolf snake with distinct white or yellow bars. Strictly nocturnal.", hi: "सफेद या पीली पट्टियों वाला छोटा कौड़िया सांप।", kn: "ಬಿಳಿ ಅಥವಾ ಹಳದಿ ಪಟ್ಟಿಗಳಿರುವ ಸಣ್ಣ ಹಾವು.", ta: "வெள்ளை அல்லது மஞ்சள் கோடுகளைக் கொண்ட ஒரு சிறிய பாம்பு.", mr: "पांढऱ्या किंवा पिवळ्या पट्ट्यांचा लहान कवड्या साप." },
    keyFeatures: { en: "Cross bars across the body; glossy black or brown; small head.", hi: "शरीर पर आड़ी पट्टियां; चमकदार काला।", kn: "ದೇಹದ ಮೇಲೆ ಅಡ್ಡ ಪಟ್ಟಿಗಳು; ಹೊಳೆಯುವ ಕಪ್ಪು ಬಣ್ಣ.", ta: "உடல் முழுவதும் குறுக்கு கோடுகள்; பளபளப்பானது.", mr: "अंगावर आडवे पट्टे; कातडी चकचकीत." },
    averageLength: "30 cm", maxLength: "50 cm",
    diet: { en: 'Lizards, skinks.', hi: 'छिपकली।', kn: 'ಹಲ್ಲಿಗಳು.', ta: 'பல்லிகள்.', mr: 'पाल, सरडे.' },
    habitat: { en: 'Forest edges, stone piles, gardens.', hi: 'पत्थरों के ढेर, बगीचे।', kn: 'ಕಲ್ಲುಗಳ ರಾಶಿ, ತೋಟಗಳು.', ta: 'பாறை குவியல்கள், தோட்டங்கள்.', mr: 'दगडांचा ढिगारा, बागा.' },
    distribution: { en: "Scattered in drier regions.", hi: "शुष्क क्षेत्रों में।", kn: "ಒಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ಕಂಡುಬರುತ್ತದೆ.", ta: "வறண்ட நிலங்களில் காணப்படும்.", mr: "कोरड्या भागात आढळतो." },
    behaviour: { en: "Nocturnal; hides under stones or leaf litter during the day.", hi: "रात्रिचर; कूड़े या पत्थरों के नीचे छुपता है।", kn: "ನಿಶಾಚರಿ; ಕಲ್ಲು ಅಥವಾ ಎಲೆಗಳ ಅಡಿ ಅಡಗಿರುತ್ತದೆ.", ta: "இரவு நேரமானது; கற்களுக்கு அடியில் ஒளியும்.", mr: "रात्री फिरणारा; दगडांखाली किंवा पालापाचोळ्यात लपतो." },
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/87070349/medium.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'banded-kukri-snake',
    name: { en: 'Banded Kukri Snake', hi: 'कुकरी', kn: 'ಕುಕ್ರಿ ಹಾವು', ta: 'வரி குக்கிரி பாம்பு', mr: 'कुकरी साप' },
    scientificName: 'Oligodon arnensis',
    vernacularNames: { en: 'Common Kukri', hi: 'कुकरी', kn: 'ಕುಕ್ರಿ ಹಾವು', ta: 'குக்கிரி பாம்பு', mr: 'कुकरी साप' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Small snake named for its curved teeth used to slice reptile eggs.", hi: "कुकरी चाकू जैसे दांतों वाला सांप जो अंडे खाने में माहिर है।", kn: "ಕುಕ್ರಿ ಕತ್ತಿಯಂತಹ ಹಲ್ಲುಗಳನ್ನು ಹೊಂದಿರುವ ಹಾವು.", ta: "குக்கிரி கத்தி போன்ற பற்களைக் கொண்ட பாம்பு.", mr: "नेपाळी कुकरीसारखे दात असलेला साप." },
    keyFeatures: { en: "V-mark on head; bold black cross-bands; smooth scales.", hi: "सिर पर V का निशान; गहरी पट्टियां।", kn: "ತಲೆಯ ಮೇಲೆ V ಗುರುತು; ದಪ್ಪ ಕಪ್ಪು ಪಟ್ಟಿಗಳು.", ta: "தலையில் V அடையாளம்; கறுப்பு பட்டைகள்.", mr: "डोक्यावर V ची खूण; ठळक आडवे पट्टे." },
    averageLength: "40 cm", maxLength: "70 cm",
    diet: { en: 'Reptile eggs, small lizards.', hi: 'अंडे, छिपकली।', kn: 'ಸರೀಸೃಪಗಳ ಮೊಟ್ಟೆಗಳು, ಹಲ್ಲಿಗಳು.', ta: 'ஊர்வன முட்டைகள், பல்லிகள்.', mr: 'अंडी, सरडे.' },
    habitat: { en: 'Gardens, rocky areas, urban settings.', hi: 'बगीचे, पथरीले इलाके।', kn: 'ತೋಟಗಳು, ಕಲ್ಲುಗಳ ಪ್ರದೇಶ.', ta: 'தோட்டங்கள், பாறை பகுதிகள்.', mr: 'बागा, खडकाळ भाग.' },
    distribution: { en: "Widespread in the region.", hi: "क्षेत्र में आम।", kn: "ಎಲ್ಲಾ ಕಡೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "பரவலாகக் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Diurnal/Nocturnal; uses curved teeth to slice reptile eggs.", hi: "रात्रिचर; अंडों को काटने के लिए दांतों का उपयोग करता है।", kn: "ನಿಶಾಚರಿ; ಮೊಟ್ಟೆಗಳನ್ನು ಕತ್ತರಿಸಲು ಹಲ್ಲುಗಳನ್ನು ಬಳಸುತ್ತದೆ.", ta: "இரவு நேரமானது; முட்டைகளை உடைக்க பற்களைப் பயன்படுத்தும்.", mr: "रात्री फिरणारा; बाकदार दातांनी अंडी फोडतो." },
    imageUrl: 'https://api.indiansnakes.org/u/1649565949783.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'streaked-kukri-snake',
    name: { en: 'Streaked Kukri Snake', hi: 'धारीदार कुकरी', kn: 'ಗೆರೆಗಳ ಕುಕ್ರಿ ಹಾವು', ta: 'கோடு குக்கிரி பாம்பு', mr: 'पट्टेरी कुकरी' },
    scientificName: 'Oligodon taeniolatus',
    vernacularNames: { en: 'Russell\'s Kukri', hi: 'कुकरी', kn: 'ಕುಕ್ರಿ ಹಾವು', ta: 'குக்கிரி பாம்பு', mr: 'कुकरी साप' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "A small, beautiful snake with streaks along the spine. Very secretive.", hi: "रीढ़ की हड्डी के साथ धारियों वाला छोटा और सुंदर सांप।", kn: "ಬೆನ್ನಿನ ಮೇಲೆ ಗೆರೆಗಳಿರುವ ಸಣ್ಣ ಸುಂದರ ಹಾವು.", ta: "முதுகெலும்பில் கோடுகளைக் கொண்ட ஒரு சிறிய பாம்பு.", mr: "पाठीवर रेषा असलेला लहान कुकरी साप." },
    keyFeatures: { en: "Fine longitudinal streaks; V-mark on head; short, rounded snout.", hi: "बारीक धारियां; सिर पर V निशान।", kn: "ಸಣ್ಣ ಉದ್ದನೆಯ ಗೆರೆಗಳು; ತಲೆಯ ಮೇಲೆ V ಗುರುತು.", ta: "மெல்லிய நீளமான கோடுகள்; தலையில் V அடையாளம்.", mr: "बारीक उभ्या रेषा; डोक्यावर V ची खूण." },
    averageLength: "30 cm", maxLength: "50 cm",
    diet: { en: 'Small lizard eggs, insects.', hi: 'अंडे, कीड़े।', kn: 'ಹಲ್ಲಿ ಮೊಟ್ಟೆಗಳು, ಕೀಟಗಳು.', ta: 'பல்லி முட்டைகள், பூச்சிகள்.', mr: 'अंडी, कीटक.' },
    habitat: { en: 'Arid areas, stone piles, plains.', hi: 'शुष्क क्षेत्र, पत्थरों के ढेर।', kn: 'ಒಣ ಪ್ರದೇಶಗಳು, ಕಲ್ಲುಗಳ ರಾಶಿ.', ta: 'வறண்ட நிலங்கள், சமவெளிகள்.', mr: 'कोरडी जमीन, माळरान.' },
    distribution: { en: "Central Freedomland regions.", hi: "मध्य फ्रीडमलैंड।", kn: "ಮಧ್ಯ ಭಾಗಗಳಲ್ಲಿ ಕಂಡುಬರುತ್ತದೆ.", ta: "மத்திய ಫ್ರೀடம்ಲೇಂಡ್.", mr: "मध्य फ्रीडमलँด." },
    behaviour: { en: "Secretive and nocturnal; often found under stones or leaf litter.", hi: "रात्रिचर; अक्सर पत्थरों के नीचे छिपा रहता है।", kn: "ನಿಶಾಚರಿ; ಕಲ್ಲುಗಳ ಅಡಿ ಅಡಗಿರುತ್ತದೆ.", ta: "இரவு நேரமானது; கற்களுக்கு அடியில் ஒளியும்.", mr: "रात्री फिरणारा; दगडांखाली लपतो." },
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/106845945/medium.jpeg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'black-headed-snake',
    name: { en: 'Dumeril’s Black-Headed Snake', hi: 'काले सिर वाला सांप', kn: 'ಕಪ್ಪು ತಲೆಯ ಹಾವು', ta: 'கறுப்புத் தலைப் பாம்பு', mr: 'काळ्या डोक्याचा साप' },
    scientificName: 'Sibynophis subpunctatus',
    vernacularNames: { en: 'Many-toothed Snake', hi: 'काले सिर वाला सांप', kn: 'ಕಪ್ಪು ತಲೆಯ ಹಾವು', ta: 'கறுப்புத் தலைப் பாம்பு', mr: 'काळ्या डोक्याचा साप' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Slender snake with a distinct black head and neck. Very agile diurnal hunter.", hi: "काले सिर और गर्दन वाला पतला सांप। शिकार में बहुत तेज।", kn: "ಕಪ್ಪು ಬಣ್ಣದ ತಲೆ ಮತ್ತು ಕುತ್ತಿಗೆಯನ್ನು ಹೊಂದಿರುವ ತೆಳುವಾದ ಹಾವು.", ta: "கருப்பு தலை மற்றும் கழுத்தைக் கொண்ட ஒரு மெல்லிய பாம்பு.", mr: "काळे डोके आणि मान असलेला पातळ साप." },
    keyFeatures: { en: "Velvety black head; small black dots along the spine; light brown body.", hi: "मखमली काला सिर; रीढ़ पर बारीक बिंदु।", kn: "ಕಪ್ಪು ಮಖಮಲಿ ತಲೆ; ಬೆನ್ನಿನ ಮೇಲೆ ಸಣ್ಣ ಚುಕ್ಕೆಗಳು.", ta: "மென்மையான கருப்பு தலை; முதுகில் கறுப்பு புள்ளிகள்.", mr: "डोके काळे; पाठीवर बारीक ठिपके." },
    averageLength: "30 cm", maxLength: "45 cm",
    diet: { en: 'Small skinks, lizards, insects.', hi: 'छिपकली।', kn: 'ಹಲ್ಲಿಗಳು.', ta: 'சிறிய பல்லிகள்.', mr: 'पाल, सरडे.' },
    habitat: { en: 'Leaf litter, grasslands, open deciduous forest.', hi: 'घास के मैदान, गीली पत्तियां।', kn: 'ಎಲೆಗಳ ರಾಶಿ, ಹುಲ್ಲುಗಾವಲುಗಳು.', ta: 'புல்வெளிகள், காடுகள்.', mr: 'गवताळ प्रदेश, पालापाचोळा.' },
    distribution: { en: "Scattered throughout the region.", hi: "पूरे क्षेत्र में।", kn: "ಎಲ್ಲಾ ಕಡೆ ಚದುರಿದಂತೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "பரவலாகக் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Diurnal; fast and alert; quick to flee when approached.", hi: "दिनचर; बहुत सतर्क और तेज भागने वाला।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ; ಅತಿ ಜಾಗರೂಕ ಮತ್ತು ವೇಗವಾಗಿ ಓಡುತ್ತದೆ.", ta: "பகலில் செயல்படும்; மிகவும் விழிப்புடன் இருக்கும்.", mr: "दिवसा सक्रिय; अत्यंत चपळ आणि वेगाने पळून जाणारा." },
    imageUrl: 'https://calphotos.berkeley.edu/imgs/512x768/0000_0000/1113/3239.jpeg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'buff-striped-keelback',
    name: { en: 'Buff-striped Keelback', hi: 'सीता की लट', kn: 'ಹಳದಿ ಪಟ್ಟಿಯ ನೀರು ಹಾವು', ta: 'நிமிர்ந்த வரிப் பாம்பு', mr: 'नानुटी' },
    scientificName: 'Amphiesma stolatum',
    vernacularNames: { en: 'Striped Keelback', hi: 'सीता की लट', kn: 'ಹಳದಿ ಪಟ್ಟಿಯ ನೀರು ಹಾವು', ta: 'நிமிர்ந்த வரிப் பாம்பு', mr: 'नानुटी' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Common non-venomous snake seen in gardens during monsoon. Docile.", hi: "मानसून में बगीचों में देखा जाने वाला आम सांप।", kn: "ಮಳೆಗಾಲದಲ್ಲಿ ತೋಟಗಳಲ್ಲಿ ಹೆಚ್ಚಾಗಿ ಕಂಡುಬರುವ ಹಾವು.", ta: "மழைக்காலத்தில் தோட்டங்களில் அதிகம் காணப்படும்.", mr: "पावसाळ्यात बागांमध्ये दिसणारा बिनविषारी साप." },
    keyFeatures: { en: "Two yellow parallel stripes along the body; keeled scales; colorful neck.", hi: "दो पीली धारियां; खुरदुरे शल्क।", kn: "ದೇಹದ ಮೇಲೆ ಎರಡು ಹಳದಿ ಪಟ್ಟಿಗಳು; ಒರಟಾದ ಚರ್ಮ.", ta: "உடல் முழுவதும் இரண்டு மஞ்சள் பட்டைகள்.", mr: "दोन पिवळ्या रेषा; मानेवर सुंदर रंग." },
    averageLength: "40 cm", maxLength: "80 cm",
    diet: { en: 'Frogs, toads, small insects.', hi: 'मेंढक और कीड़े।', kn: 'ಕಪ್ಪೆಗಳು, ಕೀಟಗಳು.', ta: 'தவளைகள், பூச்சிகள்.', mr: 'बेडूक आणि कीटक.' },
    habitat: { en: 'Wet grasslands, paddy fields, urban gardens.', hi: 'धान के खेत, बगीचे।', kn: 'ತೋಟಗಳು, ಭತ್ತದ ಗದ್ದೆಗಳು.', ta: 'தோட்டங்கள், நெல் வயல்கள்.', mr: 'बागा, भातशेती.' },
    distribution: { en: "Widespread throughout Freedomland.", hi: "व्यापक।", kn: "ಎಲ್ಲಾ ಕಡೆ ಹರಡಿದೆ.", ta: "பரவலாகக் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Diurnal and extremely docile; non-aggressive; active in rainy season.", hi: "दिनचर और बहुत शांत स्वभाव।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ ಮತ್ತು ಶಾಂತ ಸ್ವಭಾವ.", ta: "பகலில் செயல்படும்; மிகவும் சாதுவானது.", mr: "दिवसा सक्रिय आणि अतिशय गरीब स्वभावाचा." },
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdoMzKeNWxiK6cPmVscyOxjm_XzTGLmTVIpQ&s',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'olive-keelback',
    name: { en: 'Olive Keelback', hi: 'जैतूनी सांप', kn: 'ಆಲಿವ್ ನೀರು ಹಾವು', ta: 'பச்சை நீர் பாம்பு', mr: 'पाणदिवड' },
    scientificName: 'Atretium schistosum',
    vernacularNames: { en: 'Water Snake', hi: 'जैतूनी', kn: 'ನೀರು ಹಾವು', ta: 'பச்சை நீர் பாம்பு', mr: 'पाणदिवड' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "A non-venomous water snake with an olive-green hue. Very calm and aquatic.", hi: "जैतूनी हरे रंग का शांत जल सर्प।", kn: "ಆಲಿವ್ ಹಸಿರು ಬಣ್ಣದ ಶಾಂತವಾದ ನೀರು ಹಾವು.", ta: "ஆலிவ் பச்சை நிறம் கொண்ட அமைதியான நீர் பாம்பு.", mr: "जैतुनी रंगाचा शांत जलचर साप." },
    keyFeatures: { en: "Olive green body; yellow/orange belly; keeled scales; rounded snout.", hi: "जैतूनी हरा शरीर; पीला पेट।", kn: "ಆಲಿವ್ ಹಸಿರು ಮೈ; ಹಳದಿ ಬಣ್ಣದ ಹೊಟ್ಟೆ.", ta: "ஆலிவ் பச்சை உடல்; மஞ்சள் வயிறு.", mr: "जैतुनी हिरवा रंग; पोट पिवळसर." },
    averageLength: "50 cm", maxLength: "80 cm",
    diet: { en: 'Frogs, fish, tadpoles, small crabs.', hi: 'मेंढक और मछली।', kn: 'ಕಪ್ಪೆಗಳು, ಮೀನು.', ta: 'தவளைகள், மீன்.', mr: 'बेडूक, मासे.' },
    habitat: { en: 'Ponds, lakes, flooded paddy fields.', hi: 'तालाब, झीलें।', kn: 'ತಟಾಕಗಳು, ಕೆರೆಗಳು.', ta: 'குளங்கள், ஏரிகள்.', mr: 'तलाव.' },
    distribution: { en: "Common near permanent water sources.", hi: "पानी के पास आम।", kn: "ನೀರಿನ ಆಕರಗಳ ಬಳಿ ಸಾಮಾನ್ಯ.", ta: "நீர்நிலைகளுக்கு அருகில்.", mr: "पाण्याजवळ." },
    behaviour: { en: "Diurnal; aquatic; shy and retreats into water when disturbed.", hi: "दिनचर; पानी में रहना पसंद करता है।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ; ನೀರಿನಲ್ಲಿ ವಾಸಿಸುತ್ತದೆ.", ta: "பகலில் செயல்படும்; நீரில் ஒளியும்.", mr: "दिवसा सक्रिय आणि उत्तम पोहणारा." },
    imageUrl: 'https://static.inaturalist.org/photos/101306504/medium.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'checkered-keelback',
    name: { en: 'Checkered Keelback', hi: 'धोडिया', kn: 'ನೀರು ಹಾವು', ta: 'தண்ணீர் பாம்பு', mr: 'पाणदिवड' },
    scientificName: 'Fowlea piscator',
    vernacularNames: { en: 'Dhodia', hi: 'धोडिया', kn: 'ನೀರು ಹಾವು', ta: 'தண்ணೀರ್ பாம்பு', mr: 'पाणदिवड' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Common water snake found in freshwater. Plays a key role in the aquatic ecosystem.", hi: "मीठे पानी में पाया जाने वाला आम जल सर्प।", kn: "ಸಿಹಿನೀರಿನ ಆಕರಗಳಲ್ಲಿ ಕಂಡುಬರುವ ಸಾಮಾನ್ಯ ಹಾವು.", ta: "நன்னீர் நிலைகளில் காணப்படும் பொதுவான பாம்பு.", mr: "गोड्या पाण्यात आढळणारा जलचर साप." },
    keyFeatures: { en: "Checkered pattern of black spots; black streaks behind eye; keeled scales.", hi: "काले धब्बों का पैटर्न; आंख के पीछे काली रेखा।", kn: "ಚೌಕಾಕಾರದ ಕಪ್ಪು ಮಚ್ಚೆಗಳು; ಕಣ್ಣಿನ ಹಿಂದೆ ಕಪ್ಪು ಗೆರೆಗಳು.", ta: "கருப்பு புள்ளிகளின் கட்டம் போன்ற அமைப்பு.", mr: "ठिपक्यांचा चौकटीचा पॅटर्न; डोळ्यांमागे काळ्या रेषा." },
    averageLength: "80 cm", maxLength: "1.5 m",
    diet: { en: 'Fish, frogs, tadpoles.', hi: 'मछली, मेंढक।', kn: 'ಮೀನು, ಕಪ್ಪೆಗಳು.', ta: 'மீன், தவளைகள்.', mr: 'मासे, बेडूक.' },
    habitat: { en: 'Lakes, paddy fields, ponds, marshes.', hi: 'झीलें, धान के खेत।', kn: 'ಕೆರೆಗಳು, ಭತ್ತದ ಗದ್ದೆಗಳು.', ta: 'ஏரிகள், நெல் வயல்கள்.', mr: 'तलाव, भातशेती.' },
    distribution: { en: "Everywhere near freshwater bodies.", hi: "हर जगह पानी के पास।", kn: "ಎಲ್ಲಾ ಕಡೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "எங்கும் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Diurnal; highly active; can be defensive and strike repeatedly if cornered.", hi: "दिनचर; बहुत सक्रिय और पकड़ा जाने पर आक्रामक।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ; ಹಿಡಿದರೆ ಕಚ್ಚಲು ಪ್ರಯತ್ನಿಸುತ್ತದೆ.", ta: "பகலில் செயல்படும்; மிகவும் சுறுசுறுப்பானது.", mr: "दिवसा सक्रिय; पकडल्यास बचाव करण्यासाठी हल्ला करू शकतो." },
    imageUrl: 'https://punezoo.in/wp-content/uploads/2023/06/Checkered-Keelback-Water-snake-1.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'green-keelback',
    name: { en: 'Green Keelback', hi: 'हरा धोडिया', kn: 'ಹಸಿರು ನೀರು ಹಾವು', ta: 'பச்சை வரிப் பாம்பு', mr: 'हिरवी नानुटी' },
    scientificName: 'Rhabdophis plumbicolor',
    vernacularNames: { en: 'Lead-colored Keelback', hi: 'हरा धोडिया', kn: 'ಹಸಿರು ಹಾವು', ta: 'பச்சை பாம்பு', mr: 'हिरवी नानुटी' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "A stout, green snake often confused with Vipers due to its shape. Very docile.", hi: "हरा मोटा सांप जिसे अक्सर वाइपर समझ लिया जाता है लेकिन यह हानिरहित है।", kn: "ಮಂಡಲ ಹಾವಿನಂತೆ ಮಚ್ಚೆಗಳಿರುವ ದಪ್ಪವಾದ ಹಸಿರು ಬಣ್ಣದ ಹಾವು.", ta: "விரியனைப் போலத் ತೋற்றமளிக்கும் தடித்த பச்சை நிறப் பாம்பு.", mr: "घोणसासारखा दिसणारा जाड हिरवा साप. अतिशय शांत असतो." },
    keyFeatures: { en: "Dull green color; black 'V' mark on neck in young; thick body.", hi: "हरा रंग; गर्दन पर V का निशान।", kn: "ಕಡು ಹಸಿರು ಬಣ್ಣ; ಕುತ್ತಿಗೆಯ ಮೇಲೆ ಕಪ್ಪು V ಗುರುತು.", ta: "பச்சை நிறம்; கழுத்தில் கருப்பு V அடையாளம்.", mr: "हिरवा रंग; मानेवर काळी V खूण; जाड शरीर." },
    averageLength: "50 cm", maxLength: "80 cm",
    diet: { en: 'Toads, frogs, small mammals.', hi: 'मेंढक।', kn: 'ಕಪ್ಪೆಗಳು.', ta: 'தவளைகள்.', mr: 'बेडूक.' },
    habitat: { en: 'Deciduous forests, scrubland, gardens near hills.', hi: 'झाड़ीदार वन, बगीचे।', kn: 'ಅರಣ್ಯಗಳು, ತೋಟಗಳು.', ta: 'காடுகள், தோட்டங்கள்.', mr: 'झुडूप वने, बागा.' },
    distribution: { en: "Hilly forested regions.", hi: "पहाड़ी क्षेत्र।", kn: "ಬೆಟ್ಟ ಗುಡ್ಡಗಳ ಪ್ರದೇಶಗಳಲ್ಲಿ ಸಾಮಾನ್ಯ.", ta: "மலைப்பகுதிகள்.", mr: "डोंगाळ भाग." },
    behaviour: { en: "Diurnal; slow-moving; may flatten body to look larger if threatened.", hi: "दिनचर; खतरा होने पर शरीर फैला लेता है।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ; ಬೆದರಿಕೆ ಬಂದಾಗ ದೇಹವನ್ನು ಚಪ್ಪಟೆ ಮಾಡಿಕೊಳ್ಳುತ್ತದೆ.", ta: "பகலில் செயல்படும்; உடலைத் தட்டையாக்கும்.", mr: "दिवसा सक्रिय; भीती वाटल्यास शरीर पसरट करतो." },
    imageUrl: 'https://api.indiansnakes.org/u/1658084095342.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'trinket-snake',
    name: { en: 'Trinket Snake', hi: 'रूप सुंदरी', kn: 'ಅಲಂಕಾರ ಹಾವು', ta: 'அழகுப் பாம்பு', mr: 'तस्कर' },
    scientificName: 'Coelognathus helena',
    vernacularNames: { en: 'Common Trinket', hi: 'तस्कर', kn: 'ಅಲಂಕಾರ ಹಾವು', ta: 'அழகுப் பாம்பு', mr: 'तस्कर' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "A slender, active snake with beautiful patterns. Known for its graceful speed.", hi: "सुंदर निशानों वाला तेज़ और सुंदर सांप।", kn: "ಅಂದವಾದ ಗುರುತುಗಳನ್ನು ಹೊಂದಿರುವ ಅತಿ ವೇಗವಾಗಿ ಚಲಿಸುವ ಹಾವು.", ta: "அழகான அமைப்புகளைக் கொண்ட வேகமாக நகரக்கூடிய பாம்பு.", mr: "अत्यंत देखणा आणि चपळ साप. खूप वेगाने पळतो." },
    keyFeatures: { en: "Twin black streaks behind eye; bold patterns on front body; smooth scales.", hi: "आंख के पीछे काली धारियां; शरीर पर सुंदर पैटर्न।", kn: "ಕಣ್ಣಿನ ಹಿಂದೆ ಎರಡು ಕಪ್ಪು ಗೆರೆಗಳು; ದೇಹದ ಮೇಲೆ ಸುಂದರ ಗುರುತುಗಳು.", ta: "கண்ணுக்கு பின்னால் கருப்பு கோடுகள்; முன்புற உடலில் வரிகள்.", mr: "डोळ्यांच्या मागे दोन काळ्या रेषा; शरीरावर आकर्षक नक्षी." },
    averageLength: "70 cm", maxLength: "1.7 m",
    diet: { en: 'Rodents, small frogs, lizards.', hi: 'चूहे, मेंढक।', kn: 'ಇಲಿಗಳು, ಕಪ್ಪೆಗಳು.', ta: 'எலிகள், தவளைகள்.', mr: 'उंदीर, बेडूक.' },
    habitat: { en: 'Fields, urban gardens, forest edges.', hi: 'खेत, बगीचे।', kn: 'ತೋಟಗಳು, ಗದ್ದೆಗಳು.', ta: 'தோட்டங்கள், வயல்கள்.', mr: 'बागा, शेते.' },
    distribution: { en: "Widespread throughout Freedomland.", hi: "व्यापक।", kn: "ಎಲ್ಲಾ ಕಡೆ ಹರಡಿದೆ.", ta: "பரவலாகக் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Active and fast; can be snappy if caught but harmless to humans.", hi: "तेज और सक्रिय; पकड़े जाने पर आक्रामक।", kn: "ಚುರುಕಾದ ಮತ್ತು ವೇಗವಾಗಿ ಚಲಿಸುವ ಹಾವು; ಹಿಡಿದಾಗ ಕಚ್ಚಲು ಪ್ರಯತ್ನಿಸಬಹುದು.", ta: "சுறுசுறுப்பானது மற்றும் வேகமானது.", mr: "सक्रिय आणि चपळ; पकडल्यास सुरुवातीला चावा घेतो." },
    imageUrl: 'https://live.staticflickr.com/3953/15487843638_2e57bcb035_b.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'rat-snake',
    name: { en: 'Rat Snake', hi: 'धामन', kn: 'ಕೆರೆಹಾವು', ta: 'சாரைப்பாம்பு', mr: 'धामण' },
    scientificName: 'Ptyas mucosa',
    vernacularNames: { en: 'Dhaman', hi: 'धामन', kn: 'ಕೆರೆಹಾವು', ta: 'சாரைப்பாம்பு', mr: 'धामण' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "The fastest snake in the region; essential for rodent control and farmers' friend.", hi: "सबसे तेज सांप जो चूहे खाता है और किसानों का मित्र है।", kn: "ಈ ಪ್ರದೇಶದ ಅತಿ ವೇಗದ ಹಾವು; ಇಲಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ.", ta: "மிக வேகமான பாம்பு; எலிகளைக் கட்டுப்படுத்தும் விவசாயிகளின் நண்பன்.", mr: "सर्वात वेगवान साप; उंदीर फस्त करणारा शेतकऱ्याचा मित्र." },
    keyFeatures: { en: "Large eyes; black lip scales; whip-like tail; robust build.", hi: "बड़ी आंखें; काले होंठ; लंबी पूंछ।", kn: "ದೊಡ್ಡ ಕಣ್ಣುಗಳು; ಕಪ್ಪು ಬಣ್ಣದ ತುಟಿಗಳು; ಚಾವಟಿಯಂತಹ ಬಾಲ.", ta: "பெரிய கண்கள்; கருப்பு நிற உதடுகள்; சவுக்கை போன்ற வால்.", mr: "मोठे डोळे; काळी ओठ खवले; लांब शेपटी." },
    averageLength: "1.8 m", maxLength: "3.5 m",
    diet: { en: 'Rodents, frogs, birds, reptiles.', hi: 'चूहे, मेंढक।', kn: 'ಇಲಿಗಳು, ಕಪ್ಪೆಗಳು.', ta: 'எலிகள், தவளைகள்.', mr: 'उंदीर, बेडूक.' },
    habitat: { en: 'Agricultural fields, urban gardens, outskirts of cities.', hi: 'खेत, बगीचे।', kn: 'ಕೃಷಿ ಭೂಮಿ, ತೋಟಗಳು.', ta: 'வயல்கள், தோட்டங்கள்.', mr: 'शेते, बागा.' },
    distribution: { en: "Ubiquitous in rural and semi-urban areas.", hi: "हर जगह इंसानों के पास।", kn: "ಎಲ್ಲಾ ಕಡೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "எங்கும் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Diurnal and extremely fast; excellent climber; flees quickly from humans.", hi: "दिन में सक्रिय और बहुत तेज; भागने में माहिर।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ ಮತ್ತು ಅತಿ ವೇಗ; ಮರ ಹತ್ತುವುದರಲ್ಲಿ ನಿಪುಣ.", ta: "பகலில் செயல்படும்; மிக வேகமானது; கழுத்தை உப்பச் செய்யும்.", mr: "दिवसा सक्रिय आणि खूप वेगवान; चपळाईने झाडावर चढतो." },
    imageUrl: 'https://res.cloudinary.com/roundglass/image/upload/f_auto/q_auto/f_auto/c_limit,w_auto:breakpoints_200_2560_100_5:1265/v1724747049/rg/collective/media/indian-rat-snake-yellow-morph-rajesh-sanap-1724747049231.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'banded-racer',
    name: { en: 'Banded Racer', hi: 'रेसर', kn: 'ಪಟ್ಟಿಯ ಓಟದ ಹಾವು', ta: 'வரிப் பாம்பு', mr: 'रेसर' },
    scientificName: 'Platyceps plinii',
    vernacularNames: { en: 'Fast Racer', hi: 'रेसर', kn: 'ಓಟದ ಹಾವು', ta: 'வரிப் பாம்பு', mr: 'रेसर' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Alert, fast-moving snake with faint black bands. Active diurnal hunter.", hi: "सतर्क और तेज़ चलने वाला दिनचर सांप।", kn: "ಅತಿ ಜಾಗರೂಕ ಮತ್ತು ವೇಗವಾಗಿ ಚಲಿಸುವ ಹಾವು.", ta: "விழிப்புடன் இருக்கும் மற்றும் வேகமாக நகரும் பாம்பு.", mr: "चपळ आणि वेगवान साप. दिवसा वावरतो." },
    keyFeatures: { en: "Slender body; faint cross-bands; large eyes; long tail.", hi: "पतला शरीर; हल्की पट्टियां।", kn: "ತೆಳುವಾದ ಮೈ; ಕಪ್ಪು ಪಟ್ಟಿಗಳಿರಬಹುದು; ದೊಡ್ಡ ಕಣ್ಣುಗಳು.", ta: "மெலிந்த உடல்; கருப்பு பட்டைகள்.", mr: "पातळ शरीर; पुसट आडवे पट्टे." },
    averageLength: "60 cm", maxLength: "1.0 m",
    diet: { en: 'Lizards, mice, small insects.', hi: 'छिपकली।', kn: 'ಹಲ್ಲಿಗಳು, ಇಲಿಗಳು.', ta: 'பல்லிகள், எலிகள்.', mr: 'सरडे, उंदीर.' },
    habitat: { en: 'Dry grassland, scrub, open rocky plains.', hi: 'घास के मैदान।', kn: 'ಒಣ ಹುಲ್ಲುಗಾವಲುಗಳು, ಬಯಲು ಪ್ರದೇಶ.', ta: 'புልவெளிகள், புதர்கள்.', mr: 'गवताळ प्रदेश.' },
    distribution: { en: "Drier western regions of Freedomland.", hi: "पश्चिमी क्षेत्र।", kn: "ಪಶ್ಚಿಮ ಭಾಗಗಳಲ್ಲಿ ಸಾಮಾನ್ಯ.", ta: "மேற்கு ஃப்ரீடம்லேண்ட்.", mr: "पश्चिम फ्रीडमलँड." },
    behaviour: { en: "Strictly diurnal; alert; flees with lightning speed on open ground.", hi: "दिनचर; बहुत सतर्क और तेज भागने वाला।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ ಮತ್ತು ಜಾಗರೂಕ; ಅತಿ ವೇಗವಾಗಿ ಓಡುತ್ತದೆ.", ta: "பகலில் செயல்படும்; விழிப்புடன் இருக்கும்.", mr: "दिवसा सक्रिय आणि सावध; विजेच्या वेगाने पळून जातो." },
    imageUrl: 'https://d3i6msu98pdm5o.cloudfront.net/legacy/mystory/16313789910.jpeg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'bronze-back-tree-snake',
    name: { en: 'Bronzeback Tree Snake', hi: 'नंदी', kn: 'ಬೆಳ್ಳಿ ಬೆನ್ನಿನ ಹಾವು', ta: 'கொம்புப் பாம்பு', mr: 'नंदी' },
    scientificName: 'Dendrelaphis tristis',
    vernacularNames: { en: 'Tree Snake', hi: 'नंदी', kn: 'ಬೆಳ್ಳಿ ಬೆನ್ನಿನ ಹಾವು', ta: 'கொம்புப் பாம்பு', mr: 'नंदी' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Slender arboreal snake with a bronze colored back. Adapted for life in trees.", hi: "कांस्य रंग की पीठ वाला पेड़ पर रहने वाला सांप।", kn: "ಮರಗಳಲ್ಲಿ ವಾಸಿಸುವ ಹಸಿರು ಅಥವಾ ಕಂಚಿನ ಬಣ್ಣದ ಹಾವು.", ta: "வெண்கல நிற பின்புறம் கொண்ட மரப்பாம்பு.", mr: "झाडावर राहणारा पितळी रंगाचा साप. उंचीवर राहण्यासाठी अनुकूल." },
    keyFeatures: { en: "Bronze stripe along spine; flat head; large eyes; long, thin tail.", hi: "कांस्य पट्टी; सपाट सिर; बड़ी आंखें।", kn: "ಬೆನ್ನಿನ ಉದ್ದಕ್ಕೂ ಕಂಚಿನ ಬಣ್ಣದ ಪಟ್ಟಿ; ಚಪ್ಪಟೆ ತಲೆ.", ta: "முதுகெலும்பில் வெண்கலப் பட்டை; தட்டையான தலை.", mr: "पाठीवर पितळी पट्टा; डोके चपटे; डोळे मोठे." },
    averageLength: "1.0 m", maxLength: "1.5 m",
    diet: { en: 'Frogs, lizards, small birds, insects.', hi: 'मेंढक, छिपकली।', kn: 'ಕಪ್ಪೆಗಳು, ಹಲ್ಲಿಗಳು.', ta: 'தவளைகள், பல்லிகள்.', mr: 'बेडूक, सरडे.' },
    habitat: { en: 'Trees, shrubs, urban gardens, forest edges.', hi: 'पेड़, झाड़ियां।', kn: 'ಮರಗಳು, ಪೊದೆಗಳು.', ta: 'மரங்கள், புதர்கள்.', mr: 'झाडे, बागा.' },
    distribution: { en: "Widespread in forested and green areas.", hi: "व्यापक।", kn: "ಎಲ್ಲಾ ಕಡೆ ಹರಡಿದೆ.", ta: "பரவலாகக் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Active diurnal arboreal snake; very fast climber and leaper.", hi: "दिनचर; पेड़ों पर तेज चढ़ने वाला।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿ ಮರಗಳಲ್ಲಿ ವಾಸಿಸುತ್ತದೆ; ಅತಿ ವೇಗವಾಗಿ ಚಲಿಸುತ್ತದೆ.", ta: "பகலில் செயல்படும் மரப்பாம்பு; வேகமாக ஏறும் தன்மையுடையது.", mr: "दिवसा सक्रिय आणि झाडावर राहणारा; वेगाने फांद्यांवरून धावतो." },
    imageUrl: 'https://api.indiansnakes.org/u/1658171207410.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'green-vine-snake',
    name: { en: 'Green Vine Snake', hi: 'हरहरा', kn: 'ಹಸಿರು ಬಳ್ಳಿ ಹಾವು', ta: 'கண்பாம்பு', mr: 'हरणटोळ' },
    scientificName: 'Ahaetulla nasuta',
    vernacularNames: { en: 'Vine Snake', hi: 'हरहरा', kn: 'ಹಸಿರು ಹಾವು', ta: 'பச்சை பாம்பு', mr: 'हरणटोळ' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Master of camouflage; looks like a thin green vine. Unique horizontal pupils.", hi: "बेल जैसा दिखने वाला हरा सांप। छलावरण में माहिर।", kn: "ಬಳ್ಳಿಯಂತೆ ಕಾಣುವ ಹಸಿರು ಹಾವು. ಬಣ್ಣ ಬದಲಿಸಲು ನಿಪುಣ.", ta: "கொடி போலத் தோற்றமளிக்கும் பச்சை பாம்பு. உருமறைப்பில் வல்லது.", mr: "वेलीसारखा दिसणारा हिरवा साप. छलावरण करण्यात पटाईत." },
    keyFeatures: { en: "Pointed snout; leaf-green color; horizontal pupil; slender.", hi: "नुकीली नाक; हरा रंग; क्षैतिज पुतली।", kn: "ಚೂಪಾದ ಮೂತಿ; ಎಲೆಯಂತಹ ಹಸಿರು ಬಣ್ಣ; ಅಡ್ಡ ಕಣ್ಣಿನ ಪಾಪೆ.", ta: "கூர்மையான மூதி; இலை-பச்சை நிறம்.", mr: "अणकुचीदार नाक; हिरवा रंग; आडवी बाहुली." },
    averageLength: "1.0 m", maxLength: "2.0 m",
    diet: { en: 'Lizards, frogs, small birds, insects.', hi: 'छिपकली, मेंढक।', kn: 'ಹಲ್ಲಿಗಳು, ಕಪ್ಪೆಗಳು.', ta: 'பல்லிகள், தவளைகள்.', mr: 'सरडे, बेडूक.' },
    habitat: { en: 'Shrubs, low trees, forest borders, gardens.', hi: 'झाड़ियां, पेड़।', kn: 'ಪೊದೆಗಳು, ಸಣ್ಣ ಮರಗಳು.', ta: 'புதர்கள், சிறிய மரங்கள்.', mr: 'झुडपे, झाडे.' },
    distribution: { en: "Common in wet forested areas.", hi: "जंगलों में।", kn: "ಅರಣ್ಯ ಪ್ರದೇಶಗಳಲ್ಲಿ ಸಾಮಾನ್ಯ.", ta: "காடுகளின் ஓரங்களில்.", mr: "वनक्षेत्र." },
    behaviour: { en: "Diurnal; slow-moving ambush predator mimicking a vine in the wind.", hi: "दिनचर; बेल की नकल करके शिकार करता है।", kn: "ಹಗಲಿನಲ್ಲಿ ಸಕ್ರಿಯ; ಬಳ್ಳಿಯಂತೆ ನಟಿಸಿ ಬೇಟೆಯಾಡುತ್ತದೆ.", ta: "பகலில் செயல்படும்; கொடி போலப் பதுங்கி இருந்து வேட்டையாடும்.", mr: "दिवसा सक्रिय आणि झाडावर राहणारा; वेलीची नक्कल करून शिकार करतो." },
    imageUrl: 'https://live.staticflickr.com/4125/5061234407_6ac8d297e2_b.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'common-cat-snake',
    name: { en: 'Common Cat Snake', hi: 'बिल्ली सांप', kn: 'ಬೆಕ್ಕಿನ ಕಣ್ಣಿನ ಹಾವು', ta: 'பூனைப் பாம்பு', mr: 'मांजर साप' },
    scientificName: 'Boiga trigonata',
    vernacularNames: { en: 'Gamma Snake', hi: 'बिल्ली सांप', kn: 'ಬೆಕ್ಕಿನ ಕಣ್ಣಿನ ಹಾವು', ta: 'பூனைப் பாம்பு', mr: 'मांजर साप' },
    dangerLevel: SnakeDanger.HARMLESS,
    description: { en: "Nocturnal snake with vertical pupils like a cat. Defensive if disturbed.", hi: "बिल्ली जैसी आंखों वाला रात में घूमने वाला सांप।", kn: "ಬೆಕ್ಕಿನಂತೆ ಕಣ್ಣುಗಳನ್ನು ಹೊಂದಿರುವ ನಿಶಾಚರಿ ಹಾವು.", ta: "பூனை போன்ற கண்களைக் கொண்ட இரவு நேரப் பாம்பு.", mr: "मांजरासारखे डोळे असलेला रात्री फिरणारा साप." },
    keyFeatures: { en: "Vertical pupils; large triangular head; zigzag patterns; slender body.", hi: "ऊर्ध्वाधर पुतली; बड़ा सिर; टेढ़े-मेढ़े पैटर्न।", kn: "ಉದ್ದನೆಯ ಕಣ್ಣಿನ ಪಾಪೆಗಳು; ದೊಡ್ಡ ತಲೆ; ದೇಹದ ಮೇಲೆ ಅಂಕುಡೊಂಕಾದ ಗುರುತುಗಳು.", ta: "செங்குத்தான கண் பாப்பாக்கள்; பெரிய தலை.", mr: "उभी बाहुली; मोठे डोके; अंगावर नागमोडी नक्षी." },
    averageLength: "60 cm", maxLength: "1.2 m",
    diet: { en: 'Lizards, small birds, small rodents.', hi: 'छिपकली, पक्षी।', kn: 'ಹಲ್ಲಿಗಳು, ಹಕ್ಕಿಗಳು.', ta: 'பல்லிகள், பறவைகள்.', mr: 'सरडे, पक्षी.' },
    habitat: { en: 'Dry forests, scrubland, gardens, old structures.', hi: 'झाड़ियां, सूखे जंगल।', kn: 'ಒಣ ಕಾಡುಗಳು, ಪೊದೆಗಳು.', ta: 'வறண்ட காடுகள், புதர்கள்.', mr: 'कोरडी वने, बागा.' },
    distribution: { en: "Widespread in plains and hills.", hi: "व्यापक।", kn: "ಎಲ್ಲಾ ಕಡೆ ಹರಡಿದೆ.", ta: "பரவலாகக் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Nocturnal; slow-moving but vibrates tail and strikes if cornered.", hi: "रात्रिचर; खतरा होने पर पूंछ हिलाता है।", kn: "ನಿಶಾಚರಿ; ಮಂದಗತಿ ಆದರೆ ಬೆದರಿಕೆ ಬಂದಾಗ ಬಾಲವನ್ನು ಆಡಿಸುತ್ತದೆ.", ta: "இரவு நேரமானது; மிரட்டப்பட்டால் வாலை ஆட்டும்.", mr: "रात्री फिरणारा; भीती वाटल्यास शेपटी हालवून इशारा देतो." },
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/320844753/medium.jpeg',
    iucnStatus: 'Least Concern'
  },

  // VENOMOUS SPECIES (6)
  {
    id: 'spectacled-cobra',
    name: { en: 'Spectacled Cobra', hi: 'नाग', kn: 'ನಾಗರಹಾವು', ta: 'நல்ல பாம்பு', mr: 'नाग' },
    scientificName: 'Naja naja',
    vernacularNames: { en: 'Nag', hi: 'नाग', kn: 'ನಾಗರಹಾವು', ta: 'நல்ல பாம்பு', mr: 'नाग' },
    dangerLevel: SnakeDanger.VENOMOUS,
    description: { en: "Iconic snake with a majestic hood. Medically significant neurotoxic venom.", hi: "शानदार फन वाला प्रसिद्ध और जहरीला सांप।", kn: "ಭವ್ಯವಾದ ಹೆಡೆಯನ್ನು ಹೊಂದಿರುವ ಪ್ರಸಿದ್ಧ ವಿಷಪೂರಿತ ಹಾವು.", ta: "கம்பீரமான படம் கொண்ட விஷப்பாம்பு.", mr: "फणा असलेला अत्यंत विषारी साप. वैद्यकीयदृष्ट्या महत्त्वाचा." },
    keyFeatures: { en: "Spectacle mark on hood; spreads hood when threatened; smooth scales.", hi: "फन पर चश्मे का निशान; फन फैलाता है।", kn: "ಹೆಡೆಯ ಮೇಲೆ ಕನ್ನಡಿಯಂತಹ ಗುರುತು; ಬೆದರಿಕೆ ಬಂದಾಗ ಹೆಡೆ ಎತ್ತುತ್ತದೆ.", ta: "படத்தில் கண்ணாடி போன்ற அடையாளம்.", mr: "फण्यावर चष्म्याची खूण; धोका वाटल्यास फणा काढतो." },
    averageLength: "1.2 m", maxLength: "2.2 m",
    diet: { en: 'Rodents, frogs, birds, other snakes.', hi: 'चूहे, मेंढक।', kn: 'ಇಲಿಗಳು, ಕಪ್ಪೆಗಳು.', ta: 'எலிகள், தவளைகள்.', mr: 'उंदीर, बेडूक.' },
    habitat: { en: 'Agricultural fields, hollow logs, near human dwellings.', hi: 'खेत, पुराने पेड़।', kn: 'ಗದ್ದೆಗಳು, ಕೃಷಿ ಭೂಮಿ.', ta: 'வயல்கள், மரப்பொட்டரைகள்.', mr: 'शेते, जुनी झाडे.' },
    distribution: { en: "Throughout Freedomland.", hi: "हर जगह।", kn: "ಎಲ್ಲಾ ಕಡೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "எங்கும் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Diurnal/crepuscular; alert; spreads hood and hisses loudly if threatened.", hi: "दिन और शाम को सक्रिय; फन फैलाकर फुफकारता है।", kn: "ಹಗಲು ಮತ್ತು ಮುಸ್ಸಂಜೆಯಲ್ಲಿ ಸಕ್ರಿಯ; ಹೆಡೆ ಎತ್ತಿ ಸಿಸುಗುಟ್ಟುತ್ತದೆ.", ta: "பகலிலும் அந்தி வேளையிலும் செயல்படும்; படம் எடுத்து சீறும்.", mr: "दिवसा आणि सायंकाळी सक्रिय; फणा काढून फुत्कार सोडतो." },
    imageUrl: 'https://indiabiodiversity.org/files-api/api/get/crop/img//Naja%20naja/911.jpg?h=500',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'russells-viper',
    name: { en: "Russell's Viper", hi: 'कंदर', kn: 'ಮಂಡಲ ಹಾವು', ta: 'கண்ணாடி விரியன்', mr: 'घोणस' },
    scientificName: 'Daboia russelii',
    vernacularNames: { en: 'Kander', hi: 'कंदर', kn: 'ಮಂಡಲ ಹಾವು', ta: 'கண்ணாடி விரியன்', mr: 'घोणस' },
    dangerLevel: SnakeDanger.VENOMOUS,
    description: { en: "Powerful build; master of camouflage; very loud hiss like a pressure cooker.", hi: "प्रेशर कुकर जैसी फुफकार वाला जहरीला सांप।", kn: "ಪ್ರೆಶರ್ ಕುಕ್ಕರ್‌ನಂತೆ ಜೋರಾಗಿ ಸಿಸುಗುಟ್ಟುವ ವಿಷಪೂರಿತ ಹಾವು.", ta: "குக்கர் போலச் சீறும் விஷப்பாம்பு.", mr: "प्रचंड फुत्कार सोडणारा अत्यंत विषारी साप. छलावरण करण्यात पटाईत." },
    keyFeatures: { en: "Triangular head; rows of dark brown spots with white borders.", hi: "त्रिकोणीय सिर; भूरे धब्बे।", kn: "ತ್ರಿಕೋನ ತಲೆ; ಕಂದು ಬಣ್ಣದ ಮಚ್ಚೆಗಳು.", ta: "முக்கோண தலை; பழுப்பு நிற திட்டுகள்.", mr: "त्रिकोणी डोके; ठिपक्यांच्या रांगा." },
    averageLength: "1.2 m", maxLength: "1.7 m",
    diet: { en: 'Rodents, small mammals, birds.', hi: 'चूहे।', kn: 'ಇಲಿಗಳು, ಸಣ್ಣ ಸಸ್ತನಿಗಳು.', ta: 'எலிகள், பாலூட்டிகள்.', mr: 'उंदीर, सस्तन प्राणी.' },
    habitat: { en: 'Open fields, rocky terrain, shrublands.', hi: 'खेत, झाड़ियां।', kn: 'ಬಯಲು ಗದ್ದೆಗಳು, ಬಂಡೆಗಳ ಪ್ರದೇಶ.', ta: 'திறந்தவெளி வயல்கள், புதர்கள்.', mr: 'माळरान, झुडपे.' },
    distribution: { en: "Common in the region.", hi: "आम।", kn: "ಎಲ್ಲಾ ಕಡೆ ಸಾಮಾನ್ಯ.", ta: "அதிகம் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Sluggish but strikes with incredible speed; produces the loudest hiss.", hi: "सुस्त लेकिन तेज हमला करने वाला।", kn: "ಮಂದಗತಿ ಆದರೆ ವೇಗವಾಗಿ ಕಚ್ಚುತ್ತದೆ; ಜೋರಾಗಿ ಸಿಸುಗುಟ್ಟುತ್ತದೆ.", ta: "மந்தமானது; இரவு நேரமானது; மிக சத்தமாக சீறும்.", mr: "संथ पण प्रचंड वेगाने हल्ला करतो; मोठा फुत्कार सोडतो." },
    imageUrl: 'https://static.toiimg.com/thumb/msid-76646267,width-1280,height-720,resizemode-4/76646267.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'common-krait',
    name: { en: 'Common Krait', hi: 'करैत', kn: 'ಕಟ್ಟು ಹಾವು', ta: 'கட்டுவிரியன்', mr: 'मण्यार' },
    scientificName: 'Bungarus caeruleus',
    vernacularNames: { en: 'Manyar', hi: 'करैत', kn: 'ಕಟ್ಟು ಹಾವು', ta: 'கட்டுவிரியன்', mr: 'मण्यार' },
    dangerLevel: SnakeDanger.VENOMOUS,
    description: { en: "Highly venomous nocturnal hunter. Passive during day, dangerous at night.", hi: "रात का शिकारी; बहुत जहरीला।", kn: "ರಾತ್ರಿ ವೇಳೆ ಸಂಚರಿಸುವ ಅತಿ ಅಪಾಯಕಾರಿ ವಿಷಪೂರಿತ ಹಾವು.", ta: "இரவில் வேட்டையாடும் மிகவும் ஆபத்தான விஷப்பாம்பு.", mr: "रात्री शिकारीसाठी फिरणारा अत्यंत विषारी साप. दिवसा शांत असतो." },
    keyFeatures: { en: "Glossy black; thin white cross-bands (paired); hexagonal spine scales.", hi: "चमकदार काला; सफेद पट्टियां।", kn: "ಹೊಳೆಯುವ ಕಪ್ಪು ಮೈ; ಬಿಳಿ ಪಟ್ಟಿಗಳು.", ta: "பளபளப்பான கருப்பு; வெள்ளை பட்டைகள்.", mr: "चकचकीत काळा; पांढरे जोडपट्टे." },
    averageLength: "0.9 m", maxLength: "1.7 m",
    diet: { en: 'Other snakes, lizards, small rodents.', hi: 'सांप, छिपकली।', kn: 'ಇತರ ಹಾವುಗಳು, ಹಲ್ಲಿಗಳು.', ta: 'பாம்புகள், பல்லிகள்.', mr: 'इतर साप, पाल.' },
    habitat: { en: 'Termite mounds, rat holes, near dwellings.', hi: 'बिलों में, घरों के पास।', kn: 'ಇಲಿ ಬಿಲಗಳು, ಮನೆಗಳ ಹತ್ತಿರ.', ta: 'வளைகள், புற்றுகள், வீடுகளுக்கு அருகில்.', mr: 'बिळे, वारुळे, घरांच्या आसपास.' },
    distribution: { en: "Throughout Freedomland.", hi: "हर जगह।", kn: "ಎಲ್ಲಾ ಕಡೆ ಕಂಡುಬರುತ್ತದೆ.", ta: "எங்கும் காணப்படுகிறது.", mr: "सर्वत्र आढळतो." },
    behaviour: { en: "Strictly nocturnal; shy during day; potentially fatal bite if sleeping.", hi: "रात्रिचर; शर्मीला लेकिन घातक।", kn: "ಸಂಪೂರ್ಣ ನಿಶಾಚರಿ; ನಾಚಿಕೆ ಸ್ವಭಾವ ಆದರೆ ಅತಿ ಅಪಾಯಕಾರಿ.", ta: "இரவு நேரமானது; பகலில் அமைதியானது.", mr: "पूर्णपणे रात्री सक्रिय; लाजाळू पण अत्यंत घातक." },
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSHArGOPfzlFsWI3PbcesK4WzsNWUGM6TRTA&s',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'saw-scaled-viper',
    name: { en: 'Saw-scaled Viper', hi: 'फुरसा', kn: 'ಗಡಿಯಾರ ಮಂಡಲ', ta: 'சுருட்டை விரியன்', mr: 'फुुरसे' },
    scientificName: 'Echis carinatus',
    vernacularNames: { en: 'Phursa', hi: 'फुरसा', kn: 'ಗಡಿಯಾರ ಮಂಡಲ', ta: 'சுருட்டை விரಿಯன்', mr: 'फुुरसे' },
    dangerLevel: SnakeDanger.VENOMOUS,
    description: { en: "Small but aggressive; rubs scales together to produce a sawing sound.", hi: "छोटा और आक्रामक; शल्क रगड़कर आरी जैसी आवाज निकालता है।", kn: "ಸಣ್ಣ ಗಾತ್ರದ ವಿಷಪೂರಿತ ಹಾವು; ಗರಗಸದಂತಹ ಶಬ್ದ ಮಾಡುತ್ತದೆ.", ta: "அறுக்கும் சத்தம் எழுப்பும் சிறிய விஷ விரியன்.", mr: "लहान पण आक्रमक; खवले घासून करवतीसारखा आवाज काढतो." },
    keyFeatures: { en: "Light bird/cross mark on head; heavily keeled scales; small size.", hi: "सिर पर पक्षी का निशान; छोटे शल्क।", kn: "ತಲೆಯ ಮೇಲೆ ಪಕ್ಷಿಯ ಗುರುತು; ಒರಟಾದ ಚರ್ಮ; ಸಣ್ಣ ಗಾತ್ರ.", ta: "தலையில் பறவை அடையாளம்; சிறிய உடல்.", mr: "डोक्यावर पक्षाच्या पावलाची खूण; खडबडीत कातडी." },
    averageLength: "40 cm", maxLength: "80 cm",
    diet: { en: 'Insects, scorpions, small lizards, mice.', hi: 'कीड़े, बिच्छू।', kn: 'ಕೀಟಗಳು, ಚೇಳುಗಳು, ಹಲ್ಲಿಗಳು.', ta: 'பூச்சிகள், தேள்கள், பல்லிகள்.', mr: 'कीटक, विंचू, पाल.' },
    habitat: { en: 'Arid regions, rocky soil, grasslands.', hi: 'शुष्क क्षेत्र, पथरीली जमीन।', kn: 'ಒಣ ಪ್ರದೇಶಗಳು, ಬೆಟ್ಟ ಗುಡ್ಡಗಳು.', ta: 'வறண்ட நிலங்கள், பாறை பகுதிகள்.', mr: 'कोरडी जमीन, खडकाळ भाग.' },
    distribution: { en: "Dry zones of Freedomland.", hi: "शुष्क क्षेत्र।", kn: "ಒಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ಸಾಮಾನ್ಯ.", ta: "வறண்ட பகுதிகள்.", mr: "कोरडे प्रदेश." },
    behaviour: { en: "Highly alert and aggressive; makes loud rasping sound if threatened.", hi: "सतर्क और आक्रामक।", kn: "ಜಾಗರೂಕ ಮತ್ತು ಆಕ್ರಮಣಕಾರಿ; ಶಲ್ಕಗಳನ್ನು ಉಜ್ಜಿ ಶಬ್ದ ಮಾಡುತ್ತದೆ.", ta: "ஆக்ரோஷமானது; செதில்களை உரசி சத்தத்தை எழுப்பும்.", mr: "नेहमी सावध आणि डिवचल्यास आक्रमक होतो." },
    imageUrl: 'https://api.indiansnakes.org/u/1686414365666.jpg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'slender-coral-snake',
    name: { en: 'Slender Coral Snake', hi: 'मूंगा सांप', kn: 'ಹವಳದ ಹಾವು', ta: 'பவளப் பாம்பு', mr: 'पोवळ्या साप' },
    scientificName: 'Calliophis melanurus',
    vernacularNames: { en: 'Coral Snake', hi: 'मूंगा सांप', kn: 'ಹವಳದ ಹಾವು', ta: 'பவளப் பாம்பு', mr: 'पोवळ्या साप' },
    dangerLevel: SnakeDanger.VENOMOUS,
    description: { en: "A thin, brightly colored snake found in leaf litter. Highly venomous but secretive.", hi: "चमकदार रंगों वाला पतला और जहरीला सांप।", kn: "ಎಲೆಗಳ ರಾಶಿಯಲ್ಲಿ ಅಡಗಿರುವ ಸಣ್ಣ ಹವಳದ ಹಾವು.", ta: "பளபளப்பான நிறம் கொண்ட மெல்லிய விஷப்பாம்பு.", mr: "पाणांच्या ढिगाऱ्यात राहणारा लहान विषारी साप." },
    keyFeatures: { en: "Slender body; red underside of tail; small black/blue dots.", hi: "चमकदार रंग; लाल पूंछ का निचला हिस्सा।", kn: "ಹವಳದಂತಹ ಬಣ್ಣ; ತೆಳುವಾದ ಮೈ; ಕೆಂಪು ಬಣ್ಣದ ಬಾಲದ ಅಡಿಭಾಗ.", ta: "பவள நிறம்; மெலிந்த உடல்; சிவப்பான வால் பகுதி.", mr: "पोवळ्यासारखा रंग; पातळ शरीर; शेपटीचा खालचा भाग लाल." },
    averageLength: "30 cm", maxLength: "50 cm",
    diet: { en: 'Other small snakes, insects, worms.', hi: 'छोटे सांप।', kn: 'ಇತರ ಸಣ್ಣ ಹಾವುಗಳು.', ta: 'சிறிய பாம்புகள்.', mr: 'इतर लहान साप.' },
    habitat: { en: 'Forest leaf litter, grasslands, damp soil.', hi: 'जंगल, घास के मैदान।', kn: 'ಅರಣ್ಯದ ಎಲೆಗಳ ರಾಶಿ, ಹುಲ್ಲುಗಾವಲುಗಳು.', ta: 'காடுகள், புல்வெளிகள்.', mr: 'जंगले, पालापाचोळा.' },
    distribution: { en: "Scattered in wet regions.", hi: "पश्चिमी क्षेत्र।", kn: "ಪಶ್ಚಿಮ ಭಾಗಗಳಲ್ಲಿ ಕಂಡುಬರುತ್ತದೆ.", ta: "மேற்கு மலைத்தொடர்கள்.", mr: "पश्चिम घाट." },
    behaviour: { en: "Secretive and strictly nocturnal; usually avoids humans.", hi: "रात्रिचर; छेड़े जाने पर ही आक्रामक।", kn: "ನಿಶಾಚರಿ; ಅತಿ ಶಾಂತವಾಗಿದ್ದರೂ ವಿಷಪೂರಿತ.", ta: "இரவு நேரமானது; ரகசியமானது.", mr: "रात्री फिरणारा; छेडल्याशिवाय आक्रमक होत नाही." },
    imageUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/51205954/large.jpeg',
    iucnStatus: 'Least Concern'
  },
  {
    id: 'bamboo-pit-viper',
    name: { en: 'Bamboo Pit Viper', hi: 'बांस पिट वाइपर', kn: 'ಹಸಿರು ಮಂಡಲ ಹಾವು', ta: 'பச்சை விரಿಯன்', mr: 'बांबू चाफडा' },
    scientificName: 'Trimeresurus gramineus',
    vernacularNames: { en: 'Green Pit Viper', hi: 'बांस पिट वाइपर', kn: 'ಹಸಿರು ಮಂಡಲ ಹಾವು', ta: 'பச்சை விரಿಯன்', mr: 'बांबू चाफडा' },
    dangerLevel: SnakeDanger.VENOMOUS,
    description: { en: "Vibrant green arboreal snake; heat-sensing pits assist in hunting birds/frogs.", hi: "पेड़ों पर रहने वाला हरा जहरीला सांप।", kn: "ಮರಗಳಲ್ಲಿ ವಾಸಿಸುವ ಹಸಿರು ವಿಷಪೂರಿತ ಹಾವು.", ta: "மரங்களில் வாழும் பச்சை நிற விஷப்பாம்பு.", mr: "झाडावर राहणारा हिरवा विषारी साप." },
    keyFeatures: { en: "Leaf-green color; triangular head; heat-sensing pits between eyes and nostrils.", hi: "हरा रंग; त्रिकोणीय सिर।", kn: "ಎಲೆ ಹಸಿರು ಬಣ್ಣ; ತ್ರಿಕೋನ ತಲೆ; ಕಣ್ಣಿನ ಹತ್ತಿರ ಗುಳಿಗಳಿವೆ.", ta: "இலை-பச்சை நிறம்; முக்கோண தலை.", mr: "पानासारखा हिरवा रंग; त्रिकोणी डोके; उष्णता ओळखण्यासाठी खाच." },
    averageLength: "60 cm", maxLength: "1.0 m",
    diet: { en: 'Frogs, birds, small mammals, lizards.', hi: 'मेंढक, पक्षी।', kn: 'ಕಪ್ಪೆಗಳು, ಹಕ್ಕಿಗಳು, ಸಣ್ಣ ಪ್ರಾಣಿಗಳು.', ta: 'தவளைகள், பறவைகள்.', mr: 'बेडूक, पक्षी.' },
    habitat: { en: 'Bamboo thickets, high grass, shrubs, plantations.', hi: 'बांस के जंगल, चाय के बागान।', kn: 'ಬಿದಿರಿನ ಕಾಡುಗಳು, ಕಾಫಿ/ಚಹಾ ತೋಟಗಳು.', ta: 'மூங்கில் காடுகள், தோட்டங்கள்.', mr: 'बांबूची जंगले, चहाचे मळे.' },
    distribution: { en: "Hilly forested regions.", hi: "पहाड़ी क्षेत्र।", kn: "ಬೆಟ್ಟ ಗುಡ್ಡಗಳ ಅರಣ್ಯ ಪ್ರದೇಶಗಳು.", ta: "மலைப்பகுதிகள்.", mr: "डोंगाळ वनक्षेत्र." },
    behaviour: { en: "Arboreal and nocturnal; slow-moving; relies on perfect camouflage.", hi: "पेड़ों पर रहने वाला शिकारी।", kn: "ಮರಗಳಲ್ಲಿ ವಾಸಿಸುವ ನಿಶಾಚರಿ; ಮಂದಗತಿಯ ಬೇಟೆಗಾರ.", ta: "மரங்களில் பதுங்கி இருந்து வேட்டையாடும்.", mr: "झाडावर राहणारा; छलावरणावर अवलंबून राहून शिकार करतो." },
    imageUrl: 'https://live.staticflickr.com/2555/5780323617_cf9ed42009_b.jpg',
    iucnStatus: 'Least Concern'
  }
];